#pragma once

ImFont* MontserratFontLarge;
ImFont* MontserratFontMedium;
ImFont* MovingForward;
ImFont* Icons;
ImFont* RobotoRegular;

#define ENCODE_UTF8 oxorany("\xc3\xa5\xa4\xc3\xb6")
#define ICON_MIN_FA 0x21
#define ICON_MAX_FA 0xf8ff
#define ICON_FA_0 oxorany("0")	// U+30
#define ICON_FA_1 oxorany("1")	// U+31
#define ICON_FA_2 oxorany("2")	// U+32
#define ICON_FA_3 oxorany("3")	// U+33
#define ICON_FA_4 oxorany("4")	// U+34
#define ICON_FA_5 oxorany("5")	// U+35
#define ICON_FA_6 oxorany("6")	// U+36
#define ICON_FA_7 oxorany("7")	// U+37
#define ICON_FA_8 oxorany("8")	// U+38
#define ICON_FA_9 oxorany("9")	// U+39
#define ICON_FA_A oxorany("A")	// U+41
#define ICON_FA_ADDRESS_BOOK oxorany("\xef\x8a\xb9")	// U+f2b9
#define ICON_FA_ADDRESS_CARD oxorany("\xef\x8a\xbb")	// U+f2bb
#define ICON_FA_ALIGN_CENTER oxorany("\xef\x80\xb7")	// U+f037
#define ICON_FA_ALIGN_JUSTIFY oxorany("\xef\x80\xb9")	// U+f039
#define ICON_FA_ALIGN_LEFT oxorany("\xef\x80\xb6")	// U+f036
#define ICON_FA_ALIGN_RIGHT oxorany("\xef\x80\xb8")	// U+f038
#define ICON_FA_ANCHOR oxorany("\xef\x84\xbd")	// U+f13d
#define ICON_FA_ANCHOR_CIRCLE_CHECK oxorany("\xee\x92\xaa")	// U+e4aa
#define ICON_FA_ANCHOR_CIRCLE_EXCLAMATION oxorany("\xee\x92\xab")	// U+e4ab
#define ICON_FA_ANCHOR_CIRCLE_XMARK oxorany("\xee\x92\xac")	// U+e4ac
#define ICON_FA_ANCHOR_LOCK oxorany("\xee\x92\xad")	// U+e4ad
#define ICON_FA_ANGLE_DOWN oxorany("\xef\x84\x87")	// U+f107
#define ICON_FA_ANGLE_LEFT oxorany("\xef\x84\x84")	// U+f104
#define ICON_FA_ANGLE_RIGHT oxorany("\xef\x84\x85")	// U+f105
#define ICON_FA_ANGLE_UP oxorany("\xef\x84\x86")	// U+f106
#define ICON_FA_ANGLES_DOWN oxorany("\xef\x84\x83")	// U+f103
#define ICON_FA_ANGLES_LEFT oxorany("\xef\x84\x80")	// U+f100
#define ICON_FA_ANGLES_RIGHT oxorany("\xef\x84\x81")	// U+f101
#define ICON_FA_ANGLES_UP oxorany("\xef\x84\x82")	// U+f102
#define ICON_FA_ANKH oxorany("\xef\x99\x84")	// U+f644
#define ICON_FA_APPLE_WHOLE oxorany("\xef\x97\x91")	// U+f5d1
#define ICON_FA_ARCHWAY oxorany("\xef\x95\x97")	// U+f557
#define ICON_FA_ARROW_DOWN oxorany("\xef\x81\xa3")	// U+f063
#define ICON_FA_ARROW_DOWN_1_9 oxorany("\xef\x85\xa2")	// U+f162
#define ICON_FA_ARROW_DOWN_9_1 oxorany("\xef\xa2\x86")	// U+f886
#define ICON_FA_ARROW_DOWN_A_Z oxorany("\xef\x85\x9d")	// U+f15d
#define ICON_FA_ARROW_DOWN_LONG oxorany("\xef\x85\xb5")	// U+f175
#define ICON_FA_ARROW_DOWN_SHORT_WIDE oxorany("\xef\xa2\x84")	// U+f884
#define ICON_FA_ARROW_DOWN_UP_ACROSS_LINE oxorany("\xee\x92\xaf")	// U+e4af
#define ICON_FA_ARROW_DOWN_UP_LOCK oxorany("\xee\x92\xb0")	// U+e4b0
#define ICON_FA_ARROW_DOWN_WIDE_SHORT oxorany("\xef\x85\xa0")	// U+f160
#define ICON_FA_ARROW_DOWN_Z_A oxorany("\xef\xa2\x81")	// U+f881
#define ICON_FA_ARROW_LEFT oxorany("\xef\x81\xa0")	// U+f060
#define ICON_FA_ARROW_LEFT_LONG oxorany("\xef\x85\xb7")	// U+f177
#define ICON_FA_ARROW_POINTER oxorany("\xef\x89\x85")	// U+f245
#define ICON_FA_ARROW_RIGHT oxorany("\xef\x81\xa1")	// U+f061
#define ICON_FA_ARROW_RIGHT_ARROW_LEFT oxorany("\xef\x83\xac")	// U+f0ec
#define ICON_FA_ARROW_RIGHT_FROM_BRACKET oxorany("\xef\x82\x8b")	// U+f08b
#define ICON_FA_ARROW_RIGHT_LONG oxorany("\xef\x85\xb8")	// U+f178
#define ICON_FA_ARROW_RIGHT_TO_BRACKET oxorany("\xef\x82\x90")	// U+f090
#define ICON_FA_ARROW_RIGHT_TO_CITY oxorany("\xee\x92\xb3")	// U+e4b3
#define ICON_FA_ARROW_ROTATE_LEFT oxorany("\xef\x83\xa2")	// U+f0e2
#define ICON_FA_ARROW_ROTATE_RIGHT oxorany("\xef\x80\x9e")	// U+f01e
#define ICON_FA_ARROW_TREND_DOWN oxorany("\xee\x82\x97")	// U+e097
#define ICON_FA_ARROW_TREND_UP oxorany("\xee\x82\x98")	// U+e098
#define ICON_FA_ARROW_TURN_DOWN oxorany("\xef\x85\x89")	// U+f149
#define ICON_FA_ARROW_TURN_UP oxorany("\xef\x85\x88")	// U+f148
#define ICON_FA_ARROW_UP oxorany("\xef\x81\xa2")	// U+f062
#define ICON_FA_ARROW_UP_1_9 oxorany("\xef\x85\xa3")	// U+f163
#define ICON_FA_ARROW_UP_9_1 oxorany("\xef\xa2\x87")	// U+f887
#define ICON_FA_ARROW_UP_A_Z oxorany("\xef\x85\x9e")	// U+f15e
#define ICON_FA_ARROW_UP_FROM_BRACKET oxorany("\xee\x82\x9a")	// U+e09a
#define ICON_FA_ARROW_UP_FROM_GROUND_WATER oxorany("\xee\x92\xb5")	// U+e4b5
#define ICON_FA_ARROW_UP_FROM_WATER_PUMP oxorany("\xee\x92\xb6")	// U+e4b6
#define ICON_FA_ARROW_UP_LONG oxorany("\xef\x85\xb6")	// U+f176
#define ICON_FA_ARROW_UP_RIGHT_DOTS oxorany("\xee\x92\xb7")	// U+e4b7
#define ICON_FA_ARROW_UP_RIGHT_FROM_SQUARE oxorany("\xef\x82\x8e")	// U+f08e
#define ICON_FA_ARROW_UP_SHORT_WIDE oxorany("\xef\xa2\x85")	// U+f885
#define ICON_FA_ARROW_UP_WIDE_SHORT oxorany("\xef\x85\xa1")	// U+f161
#define ICON_FA_ARROW_UP_Z_A oxorany("\xef\xa2\x82")	// U+f882
#define ICON_FA_ARROWS_DOWN_TO_LINE oxorany("\xee\x92\xb8")	// U+e4b8
#define ICON_FA_ARROWS_DOWN_TO_PEOPLE oxorany("\xee\x92\xb9")	// U+e4b9
#define ICON_FA_ARROWS_LEFT_RIGHT oxorany("\xef\x81\xbe")	// U+f07e
#define ICON_FA_ARROWS_LEFT_RIGHT_TO_LINE oxorany("\xee\x92\xba")	// U+e4ba
#define ICON_FA_ARROWS_ROTATE oxorany("\xef\x80\xa1")	// U+f021
#define ICON_FA_ARROWS_SPIN oxorany("\xee\x92\xbb")	// U+e4bb
#define ICON_FA_ARROWS_SPLIT_UP_AND_LEFT oxorany("\xee\x92\xbc")	// U+e4bc
#define ICON_FA_ARROWS_TO_CIRCLE oxorany("\xee\x92\xbd")	// U+e4bd
#define ICON_FA_ARROWS_TO_DOT oxorany("\xee\x92\xbe")	// U+e4be
#define ICON_FA_ARROWS_TO_EYE oxorany("\xee\x92\xbf")	// U+e4bf
#define ICON_FA_ARROWS_TURN_RIGHT oxorany("\xee\x93\x80")	// U+e4c0
#define ICON_FA_ARROWS_TURN_TO_DOTS oxorany("\xee\x93\x81")	// U+e4c1
#define ICON_FA_ARROWS_UP_DOWN oxorany("\xef\x81\xbd")	// U+f07d
#define ICON_FA_ARROWS_UP_DOWN_LEFT_RIGHT oxorany("\xef\x81\x87")	// U+f047
#define ICON_FA_ARROWS_UP_TO_LINE oxorany("\xee\x93\x82")	// U+e4c2
#define ICON_FA_ASTERISK oxorany("*")	// U+2a
#define ICON_FA_AT oxorany("@")	// U+40
#define ICON_FA_ATOM oxorany("\xef\x97\x92")	// U+f5d2
#define ICON_FA_AUDIO_DESCRIPTION oxorany("\xef\x8a\x9e")	// U+f29e
#define ICON_FA_AUSTRAL_SIGN oxorany("\xee\x82\xa9")	// U+e0a9
#define ICON_FA_AWARD oxorany("\xef\x95\x99")	// U+f559
#define ICON_FA_B oxorany("B")	// U+42
#define ICON_FA_BABY oxorany("\xef\x9d\xbc")	// U+f77c
#define ICON_FA_BABY_CARRIAGE oxorany("\xef\x9d\xbd")	// U+f77d
#define ICON_FA_BACKWARD oxorany("\xef\x81\x8a")	// U+f04a
#define ICON_FA_BACKWARD_FAST oxorany("\xef\x81\x89")	// U+f049
#define ICON_FA_BACKWARD_STEP oxorany("\xef\x81\x88")	// U+f048
#define ICON_FA_BACON oxorany("\xef\x9f\xa5")	// U+f7e5
#define ICON_FA_BACTERIA oxorany("\xee\x81\x99")	// U+e059
#define ICON_FA_BACTERIUM oxorany("\xee\x81\x9a")	// U+e05a
#define ICON_FA_BAG_SHOPPING oxorany("\xef\x8a\x90")	// U+f290
#define ICON_FA_BAHAI oxorany("\xef\x99\xa6")	// U+f666
#define ICON_FA_BAHT_SIGN oxorany("\xee\x82\xac")	// U+e0ac
#define ICON_FA_BAN oxorany("\xef\x81\x9e")	// U+f05e
#define ICON_FA_BAN_SMOKING oxorany("\xef\x95\x8d")	// U+f54d
#define ICON_FA_BANDAGE oxorany("\xef\x91\xa2")	// U+f462
#define ICON_FA_BARCODE oxorany("\xef\x80\xaa")	// U+f02a
#define ICON_FA_BARS oxorany("\xef\x83\x89")	// U+f0c9
#define ICON_FA_BARS_PROGRESS oxorany("\xef\xa0\xa8")	// U+f828
#define ICON_FA_BARS_STAGGERED oxorany("\xef\x95\x90")	// U+f550
#define ICON_FA_BASEBALL oxorany("\xef\x90\xb3")	// U+f433
#define ICON_FA_BASEBALL_BAT_BALL oxorany("\xef\x90\xb2")	// U+f432
#define ICON_FA_BASKET_SHOPPING oxorany("\xef\x8a\x91")	// U+f291
#define ICON_FA_BASKETBALL oxorany("\xef\x90\xb4")	// U+f434
#define ICON_FA_BATH oxorany("\xef\x8b\x8d")	// U+f2cd
#define ICON_FA_BATTERY_EMPTY oxorany("\xef\x89\x84")	// U+f244
#define ICON_FA_BATTERY_FULL oxorany("\xef\x89\x80")	// U+f240
#define ICON_FA_BATTERY_HALF oxorany("\xef\x89\x82")	// U+f242
#define ICON_FA_BATTERY_QUARTER oxorany("\xef\x89\x83")	// U+f243
#define ICON_FA_BATTERY_THREE_QUARTERS oxorany("\xef\x89\x81")	// U+f241
#define ICON_FA_BED oxorany("\xef\x88\xb6")	// U+f236
#define ICON_FA_BED_PULSE oxorany("\xef\x92\x87")	// U+f487
#define ICON_FA_BEER_MUG_EMPTY oxorany("\xef\x83\xbc")	// U+f0fc
#define ICON_FA_BELL oxorany("\xef\x83\xb3")	// U+f0f3
#define ICON_FA_BELL_CONCIERGE oxorany("\xef\x95\xa2")	// U+f562
#define ICON_FA_BELL_SLASH oxorany("\xef\x87\xb6")	// U+f1f6
#define ICON_FA_BEZIER_CURVE oxorany("\xef\x95\x9b")	// U+f55b
#define ICON_FA_BICYCLE oxorany("\xef\x88\x86")	// U+f206
#define ICON_FA_BINOCULARS oxorany("\xef\x87\xa5")	// U+f1e5
#define ICON_FA_BIOHAZARD oxorany("\xef\x9e\x80")	// U+f780
#define ICON_FA_BITCOIN_SIGN oxorany("\xee\x82\xb4")	// U+e0b4
#define ICON_FA_BLENDER oxorany("\xef\x94\x97")	// U+f517
#define ICON_FA_BLENDER_PHONE oxorany("\xef\x9a\xb6")	// U+f6b6
#define ICON_FA_BLOG oxorany("\xef\x9e\x81")	// U+f781
#define ICON_FA_BOLD oxorany("\xef\x80\xb2")	// U+f032
#define ICON_FA_BOLT oxorany("\xef\x83\xa7")	// U+f0e7
#define ICON_FA_BOLT_LIGHTNING oxorany("\xee\x82\xb7")	// U+e0b7
#define ICON_FA_BOMB oxorany("\xef\x87\xa2")	// U+f1e2
#define ICON_FA_BONE oxorany("\xef\x97\x97")	// U+f5d7
#define ICON_FA_BONG oxorany("\xef\x95\x9c")	// U+f55c
#define ICON_FA_BOOK oxorany("\xef\x80\xad")	// U+f02d
#define ICON_FA_BOOK_ATLAS oxorany("\xef\x95\x98")	// U+f558
#define ICON_FA_BOOK_BIBLE oxorany("\xef\x99\x87")	// U+f647
#define ICON_FA_BOOK_BOOKMARK oxorany("\xee\x82\xbb")	// U+e0bb
#define ICON_FA_BOOK_JOURNAL_WHILLS oxorany("\xef\x99\xaa")	// U+f66a
#define ICON_FA_BOOK_MEDICAL oxorany("\xef\x9f\xa6")	// U+f7e6
#define ICON_FA_BOOK_OPEN oxorany("\xef\x94\x98")	// U+f518
#define ICON_FA_BOOK_OPEN_READER oxorany("\xef\x97\x9a")	// U+f5da
#define ICON_FA_BOOK_QURAN oxorany("\xef\x9a\x87")	// U+f687
#define ICON_FA_BOOK_SKULL oxorany("\xef\x9a\xb7")	// U+f6b7
#define ICON_FA_BOOKMARK oxorany("\xef\x80\xae")	// U+f02e
#define ICON_FA_BORDER_ALL oxorany("\xef\xa1\x8c")	// U+f84c
#define ICON_FA_BORDER_NONE oxorany("\xef\xa1\x90")	// U+f850
#define ICON_FA_BORDER_TOP_LEFT oxorany("\xef\xa1\x93")	// U+f853
#define ICON_FA_BORE_HOLE oxorany("\xee\x93\x83")	// U+e4c3
#define ICON_FA_BOTTLE_DROPLET oxorany("\xee\x93\x84")	// U+e4c4
#define ICON_FA_BOTTLE_WATER oxorany("\xee\x93\x85")	// U+e4c5
#define ICON_FA_BOWL_FOOD oxorany("\xee\x93\x86")	// U+e4c6
#define ICON_FA_BOWL_RICE oxorany("\xee\x8b\xab")	// U+e2eb
#define ICON_FA_BOWLING_BALL oxorany("\xef\x90\xb6")	// U+f436
#define ICON_FA_BOX oxorany("\xef\x91\xa6")	// U+f466
#define ICON_FA_BOX_ARCHIVE oxorany("\xef\x86\x87")	// U+f187
#define ICON_FA_BOX_OPEN oxorany("\xef\x92\x9e")	// U+f49e
#define ICON_FA_BOX_TISSUE oxorany("\xee\x81\x9b")	// U+e05b
#define ICON_FA_BOXES_PACKING oxorany("\xee\x93\x87")	// U+e4c7
#define ICON_FA_BOXES_STACKED oxorany("\xef\x91\xa8")	// U+f468
#define ICON_FA_BRAILLE oxorany("\xef\x8a\xa1")	// U+f2a1
#define ICON_FA_BRAIN oxorany("\xef\x97\x9c")	// U+f5dc
#define ICON_FA_BRAZILIAN_REAL_SIGN oxorany("\xee\x91\xac")	// U+e46c
#define ICON_FA_BREAD_SLICE oxorany("\xef\x9f\xac")	// U+f7ec
#define ICON_FA_BRIDGE oxorany("\xee\x93\x88")	// U+e4c8
#define ICON_FA_BRIDGE_CIRCLE_CHECK oxorany("\xee\x93\x89")	// U+e4c9
#define ICON_FA_BRIDGE_CIRCLE_EXCLAMATION oxorany("\xee\x93\x8a")	// U+e4ca
#define ICON_FA_BRIDGE_CIRCLE_XMARK oxorany("\xee\x93\x8b")	// U+e4cb
#define ICON_FA_BRIDGE_LOCK oxorany("\xee\x93\x8c")	// U+e4cc
#define ICON_FA_BRIDGE_WATER oxorany("\xee\x93\x8e")	// U+e4ce
#define ICON_FA_BRIEFCASE oxorany("\xef\x82\xb1")	// U+f0b1
#define ICON_FA_BRIEFCASE_MEDICAL oxorany("\xef\x91\xa9")	// U+f469
#define ICON_FA_BROOM oxorany("\xef\x94\x9a")	// U+f51a
#define ICON_FA_BROOM_BALL oxorany("\xef\x91\x98")	// U+f458
#define ICON_FA_BRUSH oxorany("\xef\x95\x9d")	// U+f55d
#define ICON_FA_BUCKET oxorany("\xee\x93\x8f")	// U+e4cf
#define ICON_FA_BUG oxorany("\xef\x86\x88")	// U+f188
#define ICON_FA_BUG_SLASH oxorany("\xee\x92\x90")	// U+e490
#define ICON_FA_BUGS oxorany("\xee\x93\x90")	// U+e4d0
#define ICON_FA_BUILDING oxorany("\xef\x86\xad")	// U+f1ad
#define ICON_FA_BUILDING_CIRCLE_ARROW_RIGHT oxorany("\xee\x93\x91")	// U+e4d1
#define ICON_FA_BUILDING_CIRCLE_CHECK oxorany("\xee\x93\x92")	// U+e4d2
#define ICON_FA_BUILDING_CIRCLE_EXCLAMATION oxorany("\xee\x93\x93")	// U+e4d3
#define ICON_FA_BUILDING_CIRCLE_XMARK oxorany("\xee\x93\x94")	// U+e4d4
#define ICON_FA_BUILDING_COLUMNS oxorany("\xef\x86\x9c")	// U+f19c
#define ICON_FA_BUILDING_FLAG oxorany("\xee\x93\x95")	// U+e4d5
#define ICON_FA_BUILDING_LOCK oxorany("\xee\x93\x96")	// U+e4d6
#define ICON_FA_BUILDING_NGO oxorany("\xee\x93\x97")	// U+e4d7
#define ICON_FA_BUILDING_SHIELD oxorany("\xee\x93\x98")	// U+e4d8
#define ICON_FA_BUILDING_UN oxorany("\xee\x93\x99")	// U+e4d9
#define ICON_FA_BUILDING_USER oxorany("\xee\x93\x9a")	// U+e4da
#define ICON_FA_BUILDING_WHEAT oxorany("\xee\x93\x9b")	// U+e4db
#define ICON_FA_BULLHORN oxorany("\xef\x82\xa1")	// U+f0a1
#define ICON_FA_BULLSEYE oxorany("\xef\x85\x80")	// U+f140
#define ICON_FA_BURGER oxorany("\xef\xa0\x85")	// U+f805
#define ICON_FA_BURST oxorany("\xee\x93\x9c")	// U+e4dc
#define ICON_FA_BUS oxorany("\xef\x88\x87")	// U+f207
#define ICON_FA_BUS_SIMPLE oxorany("\xef\x95\x9e")	// U+f55e
#define ICON_FA_BUSINESS_TIME oxorany("\xef\x99\x8a")	// U+f64a
#define ICON_FA_C oxorany("C")	// U+43
#define ICON_FA_CAKE_CANDLES oxorany("\xef\x87\xbd")	// U+f1fd
#define ICON_FA_CALCULATOR oxorany("\xef\x87\xac")	// U+f1ec
#define ICON_FA_CALENDAR oxorany("\xef\x84\xb3")	// U+f133
#define ICON_FA_CALENDAR_CHECK oxorany("\xef\x89\xb4")	// U+f274
#define ICON_FA_CALENDAR_DAY oxorany("\xef\x9e\x83")	// U+f783
#define ICON_FA_CALENDAR_DAYS oxorany("\xef\x81\xb3")	// U+f073
#define ICON_FA_CALENDAR_MINUS oxorany("\xef\x89\xb2")	// U+f272
#define ICON_FA_CALENDAR_PLUS oxorany("\xef\x89\xb1")	// U+f271
#define ICON_FA_CALENDAR_WEEK oxorany("\xef\x9e\x84")	// U+f784
#define ICON_FA_CALENDAR_XMARK oxorany("\xef\x89\xb3")	// U+f273
#define ICON_FA_CAMERA oxorany("\xef\x80\xb0")	// U+f030
#define ICON_FA_CAMERA_RETRO oxorany("\xef\x82\x83")	// U+f083
#define ICON_FA_CAMERA_ROTATE oxorany("\xee\x83\x98")	// U+e0d8
#define ICON_FA_CAMPGROUND oxorany("\xef\x9a\xbb")	// U+f6bb
#define ICON_FA_CANDY_CANE oxorany("\xef\x9e\x86")	// U+f786
#define ICON_FA_CANNABIS oxorany("\xef\x95\x9f")	// U+f55f
#define ICON_FA_CAPSULES oxorany("\xef\x91\xab")	// U+f46b
#define ICON_FA_CAR oxorany("\xef\x86\xb9")	// U+f1b9
#define ICON_FA_CAR_BATTERY oxorany("\xef\x97\x9f")	// U+f5df
#define ICON_FA_CAR_BURST oxorany("\xef\x97\xa1")	// U+f5e1
#define ICON_FA_CAR_ON oxorany("\xee\x93\x9d")	// U+e4dd
#define ICON_FA_CAR_REAR oxorany("\xef\x97\x9e")	// U+f5de
#define ICON_FA_CAR_SIDE oxorany("\xef\x97\xa4")	// U+f5e4
#define ICON_FA_CAR_TUNNEL oxorany("\xee\x93\x9e")	// U+e4de
#define ICON_FA_CARAVAN oxorany("\xef\xa3\xbf")	// U+f8ff
#define ICON_FA_CARET_DOWN oxorany("\xef\x83\x97")	// U+f0d7
#define ICON_FA_CARET_LEFT oxorany("\xef\x83\x99")	// U+f0d9
#define ICON_FA_CARET_RIGHT oxorany("\xef\x83\x9a")	// U+f0da
#define ICON_FA_CARET_UP oxorany("\xef\x83\x98")	// U+f0d8
#define ICON_FA_CARROT oxorany("\xef\x9e\x87")	// U+f787
#define ICON_FA_CART_ARROW_DOWN oxorany("\xef\x88\x98")	// U+f218
#define ICON_FA_CART_FLATBED oxorany("\xef\x91\xb4")	// U+f474
#define ICON_FA_CART_FLATBED_SUITCASE oxorany("\xef\x96\x9d")	// U+f59d
#define ICON_FA_CART_PLUS oxorany("\xef\x88\x97")	// U+f217
#define ICON_FA_CART_SHOPPING oxorany("\xef\x81\xba")	// U+f07a
#define ICON_FA_CASH_REGISTER oxorany("\xef\x9e\x88")	// U+f788
#define ICON_FA_CAT oxorany("\xef\x9a\xbe")	// U+f6be
#define ICON_FA_CEDI_SIGN oxorany("\xee\x83\x9f")	// U+e0df
#define ICON_FA_CENT_SIGN oxorany("\xee\x8f\xb5")	// U+e3f5
#define ICON_FA_CERTIFICATE oxorany("\xef\x82\xa3")	// U+f0a3
#define ICON_FA_CHAIR oxorany("\xef\x9b\x80")	// U+f6c0
#define ICON_FA_CHALKBOARD oxorany("\xef\x94\x9b")	// U+f51b
#define ICON_FA_CHALKBOARD_USER oxorany("\xef\x94\x9c")	// U+f51c
#define ICON_FA_CHAMPAGNE_GLASSES oxorany("\xef\x9e\x9f")	// U+f79f
#define ICON_FA_CHARGING_STATION oxorany("\xef\x97\xa7")	// U+f5e7
#define ICON_FA_CHART_AREA oxorany("\xef\x87\xbe")	// U+f1fe
#define ICON_FA_CHART_BAR oxorany("\xef\x82\x80")	// U+f080
#define ICON_FA_CHART_COLUMN oxorany("\xee\x83\xa3")	// U+e0e3
#define ICON_FA_CHART_GANTT oxorany("\xee\x83\xa4")	// U+e0e4
#define ICON_FA_CHART_LINE oxorany("\xef\x88\x81")	// U+f201
#define ICON_FA_CHART_PIE oxorany("\xef\x88\x80")	// U+f200
#define ICON_FA_CHART_SIMPLE oxorany("\xee\x91\xb3")	// U+e473
#define ICON_FA_CHECK oxorany("\xef\x80\x8c")	// U+f00c
#define ICON_FA_CHECK_DOUBLE oxorany("\xef\x95\xa0")	// U+f560
#define ICON_FA_CHECK_TO_SLOT oxorany("\xef\x9d\xb2")	// U+f772
#define ICON_FA_CHEESE oxorany("\xef\x9f\xaf")	// U+f7ef
#define ICON_FA_CHESS oxorany("\xef\x90\xb9")	// U+f439
#define ICON_FA_CHESS_BISHOP oxorany("\xef\x90\xba")	// U+f43a
#define ICON_FA_CHESS_BOARD oxorany("\xef\x90\xbc")	// U+f43c
#define ICON_FA_CHESS_KING oxorany("\xef\x90\xbf")	// U+f43f
#define ICON_FA_CHESS_KNIGHT oxorany("\xef\x91\x81")	// U+f441
#define ICON_FA_CHESS_PAWN oxorany("\xef\x91\x83")	// U+f443
#define ICON_FA_CHESS_QUEEN oxorany("\xef\x91\x85")	// U+f445
#define ICON_FA_CHESS_ROOK oxorany("\xef\x91\x87")	// U+f447
#define ICON_FA_CHEVRON_DOWN oxorany("\xef\x81\xb8")	// U+f078
#define ICON_FA_CHEVRON_LEFT oxorany("\xef\x81\x93")	// U+f053
#define ICON_FA_CHEVRON_RIGHT oxorany("\xef\x81\x94")	// U+f054
#define ICON_FA_CHEVRON_UP oxorany("\xef\x81\xb7")	// U+f077
#define ICON_FA_CHILD oxorany("\xef\x86\xae")	// U+f1ae
#define ICON_FA_CHILD_RIFLE oxorany("\xee\x93\xa0")	// U+e4e0
#define ICON_FA_CHILDREN oxorany("\xee\x93\xa1")	// U+e4e1
#define ICON_FA_CHURCH oxorany("\xef\x94\x9d")	// U+f51d
#define ICON_FA_CIRCLE oxorany("\xef\x84\x91")	// U+f111
#define ICON_FA_CIRCLE_ARROW_DOWN oxorany("\xef\x82\xab")	// U+f0ab
#define ICON_FA_CIRCLE_ARROW_LEFT oxorany("\xef\x82\xa8")	// U+f0a8
#define ICON_FA_CIRCLE_ARROW_RIGHT oxorany("\xef\x82\xa9")	// U+f0a9
#define ICON_FA_CIRCLE_ARROW_UP oxorany("\xef\x82\xaa")	// U+f0aa
#define ICON_FA_CIRCLE_CHECK oxorany("\xef\x81\x98")	// U+f058
#define ICON_FA_CIRCLE_CHEVRON_DOWN oxorany("\xef\x84\xba")	// U+f13a
#define ICON_FA_CIRCLE_CHEVRON_LEFT oxorany("\xef\x84\xb7")	// U+f137
#define ICON_FA_CIRCLE_CHEVRON_RIGHT oxorany("\xef\x84\xb8")	// U+f138
#define ICON_FA_CIRCLE_CHEVRON_UP oxorany("\xef\x84\xb9")	// U+f139
#define ICON_FA_CIRCLE_DOLLAR_TO_SLOT oxorany("\xef\x92\xb9")	// U+f4b9
#define ICON_FA_CIRCLE_DOT oxorany("\xef\x86\x92")	// U+f192
#define ICON_FA_CIRCLE_DOWN oxorany("\xef\x8d\x98")	// U+f358
#define ICON_FA_CIRCLE_EXCLAMATION oxorany("\xef\x81\xaa")	// U+f06a
#define ICON_FA_CIRCLE_H oxorany("\xef\x91\xbe")	// U+f47e
#define ICON_FA_CIRCLE_HALF_STROKE oxorany("\xef\x81\x82")	// U+f042
#define ICON_FA_TRANSPORTER u8"\ue042"
#define ICON_FA_CIRCLE_INFO oxorany("\xef\x81\x9a")	// U+f05a
#define ICON_FA_CIRCLE_LEFT oxorany("\xef\x8d\x99")	// U+f359
#define ICON_FA_CIRCLE_MINUS oxorany("\xef\x81\x96")	// U+f056
#define ICON_FA_CIRCLE_NODES oxorany("\xee\x93\xa2")	// U+e4e2
#define ICON_FA_CIRCLE_NOTCH oxorany("\xef\x87\x8e")	// U+f1ce
#define ICON_FA_CIRCLE_PAUSE oxorany("\xef\x8a\x8b")	// U+f28b
#define ICON_FA_CIRCLE_PLAY oxorany("\xef\x85\x84")	// U+f144
#define ICON_FA_CIRCLE_PLUS oxorany("\xef\x81\x95")	// U+f055
#define ICON_FA_CIRCLE_QUESTION oxorany("\xef\x81\x99")	// U+f059
#define ICON_FA_CIRCLE_RADIATION oxorany("\xef\x9e\xba")	// U+f7ba
#define ICON_FA_CIRCLE_RIGHT oxorany("\xef\x8d\x9a")	// U+f35a
#define ICON_FA_CIRCLE_STOP oxorany("\xef\x8a\x8d")	// U+f28d
#define ICON_FA_CIRCLE_UP oxorany("\xef\x8d\x9b")	// U+f35b
#define ICON_FA_CIRCLE_USER oxorany("\xef\x8a\xbd")	// U+f2bd
#define ICON_FA_CIRCLE_XMARK oxorany("\xef\x81\x97")	// U+f057
#define ICON_FA_CITY oxorany("\xef\x99\x8f")	// U+f64f
#define ICON_FA_CLAPPERBOARD oxorany("\xee\x84\xb1")	// U+e131
#define ICON_FA_CLIPBOARD oxorany("\xef\x8c\xa8")	// U+f328
#define ICON_FA_CLIPBOARD_CHECK oxorany("\xef\x91\xac")	// U+f46c
#define ICON_FA_CLIPBOARD_LIST oxorany("\xef\x91\xad")	// U+f46d
#define ICON_FA_CLIPBOARD_QUESTION oxorany("\xee\x93\xa3")	// U+e4e3
#define ICON_FA_CLIPBOARD_USER oxorany("\xef\x9f\xb3")	// U+f7f3
#define ICON_FA_CLOCK oxorany("\xef\x80\x97")	// U+f017
#define ICON_FA_CLOCK_ROTATE_LEFT oxorany("\xef\x87\x9a")	// U+f1da
#define ICON_FA_CLONE oxorany("\xef\x89\x8d")	// U+f24d
#define ICON_FA_CLOSED_CAPTIONING oxorany("\xef\x88\x8a")	// U+f20a
#define ICON_FA_CLOUD oxorany("\xef\x83\x82")	// U+f0c2
#define ICON_FA_CLOUD_ARROW_DOWN oxorany("\xef\x83\xad")	// U+f0ed
#define ICON_FA_CLOUD_ARROW_UP oxorany("\xef\x83\xae")	// U+f0ee
#define ICON_FA_CLOUD_BOLT oxorany("\xef\x9d\xac")	// U+f76c
#define ICON_FA_CLOUD_MEATBALL oxorany("\xef\x9c\xbb")	// U+f73b
#define ICON_FA_CLOUD_MOON oxorany("\xef\x9b\x83")	// U+f6c3
#define ICON_FA_CLOUD_MOON_RAIN oxorany("\xef\x9c\xbc")	// U+f73c
#define ICON_FA_CLOUD_RAIN oxorany("\xef\x9c\xbd")	// U+f73d
#define ICON_FA_CLOUD_SHOWERS_HEAVY oxorany("\xef\x9d\x80")	// U+f740
#define ICON_FA_CLOUD_SHOWERS_WATER oxorany("\xee\x93\xa4")	// U+e4e4
#define ICON_FA_CLOUD_SUN oxorany("\xef\x9b\x84")	// U+f6c4
#define ICON_FA_CLOUD_SUN_RAIN oxorany("\xef\x9d\x83")	// U+f743
#define ICON_FA_CLOVER oxorany("\xee\x84\xb9")	// U+e139
#define ICON_FA_CODE oxorany("\xef\x84\xa1")	// U+f121
#define ICON_FA_CODE_BRANCH oxorany("\xef\x84\xa6")	// U+f126
#define ICON_FA_CODE_COMMIT oxorany("\xef\x8e\x86")	// U+f386
#define ICON_FA_CODE_COMPARE oxorany("\xee\x84\xba")	// U+e13a
#define ICON_FA_CODE_FORK oxorany("\xee\x84\xbb")	// U+e13b
#define ICON_FA_CODE_MERGE oxorany("\xef\x8e\x87")	// U+f387
#define ICON_FA_CODE_PULL_REQUEST oxorany("\xee\x84\xbc")	// U+e13c
#define ICON_FA_COINS oxorany("\xef\x94\x9e")	// U+f51e
#define ICON_FA_COLON_SIGN oxorany("\xee\x85\x80")	// U+e140
#define ICON_FA_COMMENT oxorany("\xef\x81\xb5")	// U+f075
#define ICON_FA_COMMENT_DOLLAR oxorany("\xef\x99\x91")	// U+f651
#define ICON_FA_COMMENT_DOTS oxorany("\xef\x92\xad")	// U+f4ad
#define ICON_FA_COMMENT_MEDICAL oxorany("\xef\x9f\xb5")	// U+f7f5
#define ICON_FA_COMMENT_SLASH oxorany("\xef\x92\xb3")	// U+f4b3
#define ICON_FA_COMMENT_SMS oxorany("\xef\x9f\x8d")	// U+f7cd
#define ICON_FA_COMMENTS oxorany("\xef\x82\x86")	// U+f086
#define ICON_FA_COMMENTS_DOLLAR oxorany("\xef\x99\x93")	// U+f653
#define ICON_FA_COMPACT_DISC oxorany("\xef\x94\x9f")	// U+f51f
#define ICON_FA_COMPASS oxorany("\xef\x85\x8e")	// U+f14e
#define ICON_FA_COMPASS_DRAFTING oxorany("\xef\x95\xa8")	// U+f568
#define ICON_FA_COMPRESS oxorany("\xef\x81\xa6")	// U+f066
#define ICON_FA_COMPUTER oxorany("\xee\x93\xa5")	// U+e4e5
#define ICON_FA_COMPUTER_MOUSE oxorany("\xef\xa3\x8c")	// U+f8cc
#define ICON_FA_COOKIE oxorany("\xef\x95\xa3")	// U+f563
#define ICON_FA_COOKIE_BITE oxorany("\xef\x95\xa4")	// U+f564
#define ICON_FA_COPY oxorany("\xef\x83\x85")	// U+f0c5
#define ICON_FA_COPYRIGHT oxorany("\xef\x87\xb9")	// U+f1f9
#define ICON_FA_COUCH oxorany("\xef\x92\xb8")	// U+f4b8
#define ICON_FA_COW oxorany("\xef\x9b\x88")	// U+f6c8
#define ICON_FA_CREDIT_CARD oxorany("\xef\x82\x9d")	// U+f09d
#define ICON_FA_CROP oxorany("\xef\x84\xa5")	// U+f125
#define ICON_FA_CROP_SIMPLE oxorany("\xef\x95\xa5")	// U+f565
#define ICON_FA_CROSS oxorany("\xef\x99\x94")	// U+f654
#define ICON_FA_CROSSHAIRS oxorany("\xef\x81\x9b")	// U+f05b
#define ICON_FA_CROW oxorany("\xef\x94\xa0")	// U+f520
#define ICON_FA_CROWN oxorany("\xef\x94\xa1")	// U+f521
#define ICON_FA_CRUTCH oxorany("\xef\x9f\xb7")	// U+f7f7
#define ICON_FA_CRUZEIRO_SIGN oxorany("\xee\x85\x92")	// U+e152
#define ICON_FA_CUBE oxorany("\xef\x86\xb2")	// U+f1b2
#define ICON_FA_CUBES oxorany("\xef\x86\xb3")	// U+f1b3
#define ICON_FA_CUBES_STACKED oxorany("\xee\x93\xa6")	// U+e4e6
#define ICON_FA_D oxorany("D")	// U+44
#define ICON_FA_DATABASE oxorany("\xef\x87\x80")	// U+f1c0
#define ICON_FA_DELETE_LEFT oxorany("\xef\x95\x9a")	// U+f55a
#define ICON_FA_DEMOCRAT oxorany("\xef\x9d\x87")	// U+f747
#define ICON_FA_DESKTOP oxorany("\xef\x8e\x90")	// U+f390
#define ICON_FA_DHARMACHAKRA oxorany("\xef\x99\x95")	// U+f655
#define ICON_FA_DIAGRAM_NEXT oxorany("\xee\x91\xb6")	// U+e476
#define ICON_FA_DIAGRAM_PREDECESSOR oxorany("\xee\x91\xb7")	// U+e477
#define ICON_FA_DIAGRAM_PROJECT oxorany("\xef\x95\x82")	// U+f542
#define ICON_FA_DIAGRAM_SUCCESSOR oxorany("\xee\x91\xba")	// U+e47a
#define ICON_FA_DIAMOND oxorany("\xef\x88\x99")	// U+f219
#define ICON_FA_DIAMOND_TURN_RIGHT oxorany("\xef\x97\xab")	// U+f5eb
#define ICON_FA_DICE oxorany("\xef\x94\xa2")	// U+f522
#define ICON_FA_DICE_D20 oxorany("\xef\x9b\x8f")	// U+f6cf
#define ICON_FA_DICE_D6 oxorany("\xef\x9b\x91")	// U+f6d1
#define ICON_FA_DICE_FIVE oxorany("\xef\x94\xa3")	// U+f523
#define ICON_FA_DICE_FOUR oxorany("\xef\x94\xa4")	// U+f524
#define ICON_FA_DICE_ONE oxorany("\xef\x94\xa5")	// U+f525
#define ICON_FA_DICE_SIX oxorany("\xef\x94\xa6")	// U+f526
#define ICON_FA_DICE_THREE oxorany("\xef\x94\xa7")	// U+f527
#define ICON_FA_DICE_TWO oxorany("\xef\x94\xa8")	// U+f528
#define ICON_FA_DISEASE oxorany("\xef\x9f\xba")	// U+f7fa
#define ICON_FA_DISPLAY oxorany("\xee\x85\xa3")	// U+e163
#define ICON_FA_DIVIDE oxorany("\xef\x94\xa9")	// U+f529
#define ICON_FA_DNA oxorany("\xef\x91\xb1")	// U+f471
#define ICON_FA_DOG oxorany("\xef\x9b\x93")	// U+f6d3
#define ICON_FA_DOLLAR_SIGN oxorany("$")	// U+24
#define ICON_FA_DOLLY oxorany("\xef\x91\xb2")	// U+f472
#define ICON_FA_DONG_SIGN oxorany("\xee\x85\xa9")	// U+e169
#define ICON_FA_DOOR_CLOSED oxorany("\xef\x94\xaa")	// U+f52a
#define ICON_FA_DOOR_OPEN oxorany("\xef\x94\xab")	// U+f52b
#define ICON_FA_DOVE oxorany("\xef\x92\xba")	// U+f4ba
#define ICON_FA_DOWN_LEFT_AND_UP_RIGHT_TO_CENTER oxorany("\xef\x90\xa2")	// U+f422
#define ICON_FA_DOWN_LONG oxorany("\xef\x8c\x89")	// U+f309
#define ICON_FA_DOWNLOAD oxorany("\xef\x80\x99")	// U+f019
#define ICON_FA_DRAGON oxorany("\xef\x9b\x95")	// U+f6d5
#define ICON_FA_DRAW_POLYGON oxorany("\xef\x97\xae")	// U+f5ee
#define ICON_FA_DROPLET oxorany("\xef\x81\x83")	// U+f043
#define ICON_FA_DROPLET_SLASH oxorany("\xef\x97\x87")	// U+f5c7
#define ICON_FA_DRUM oxorany("\xef\x95\xa9")	// U+f569
#define ICON_FA_DRUM_STEELPAN oxorany("\xef\x95\xaa")	// U+f56a
#define ICON_FA_DRUMSTICK_BITE oxorany("\xef\x9b\x97")	// U+f6d7
#define ICON_FA_DUMBBELL oxorany("\xef\x91\x8b")	// U+f44b
#define ICON_FA_DUMPSTER oxorany("\xef\x9e\x93")	// U+f793
#define ICON_FA_DUMPSTER_FIRE oxorany("\xef\x9e\x94")	// U+f794
#define ICON_FA_DUNGEON oxorany("\xef\x9b\x99")	// U+f6d9
#define ICON_FA_E oxorany("E")	// U+45
#define ICON_FA_EAR_DEAF oxorany("\xef\x8a\xa4")	// U+f2a4
#define ICON_FA_EAR_LISTEN oxorany("\xef\x8a\xa2")	// U+f2a2
#define ICON_FA_EARTH_AFRICA oxorany("\xef\x95\xbc")	// U+f57c
#define ICON_FA_EARTH_AMERICAS oxorany("\xef\x95\xbd")	// U+f57d
#define ICON_FA_EARTH_ASIA oxorany("\xef\x95\xbe")	// U+f57e
#define ICON_FA_EARTH_EUROPE oxorany("\xef\x9e\xa2")	// U+f7a2
#define ICON_FA_EARTH_OCEANIA oxorany("\xee\x91\xbb")	// U+e47b
#define ICON_FA_EGG oxorany("\xef\x9f\xbb")	// U+f7fb
#define ICON_FA_EJECT oxorany("\xef\x81\x92")	// U+f052
#define ICON_FA_ELEVATOR oxorany("\xee\x85\xad")	// U+e16d
#define ICON_FA_ELLIPSIS oxorany("\xef\x85\x81")	// U+f141
#define ICON_FA_ELLIPSIS_VERTICAL oxorany("\xef\x85\x82")	// U+f142
#define ICON_FA_ENVELOPE oxorany("\xef\x83\xa0")	// U+f0e0
#define ICON_FA_ENVELOPE_CIRCLE_CHECK oxorany("\xee\x93\xa8")	// U+e4e8
#define ICON_FA_ENVELOPE_OPEN oxorany("\xef\x8a\xb6")	// U+f2b6
#define ICON_FA_ENVELOPE_OPEN_TEXT oxorany("\xef\x99\x98")	// U+f658
#define ICON_FA_ENVELOPES_BULK oxorany("\xef\x99\xb4")	// U+f674
#define ICON_FA_EQUALS oxorany("=")	// U+3d
#define ICON_FA_ERASER oxorany("\xef\x84\xad")	// U+f12d
#define ICON_FA_ETHERNET oxorany("\xef\x9e\x96")	// U+f796
#define ICON_FA_EURO_SIGN oxorany("\xef\x85\x93")	// U+f153
#define ICON_FA_EXCLAMATION oxorany("!")	// U+21
#define ICON_FA_EXPAND oxorany("\xef\x81\xa5")	// U+f065
#define ICON_FA_EXPLOSION oxorany("\xee\x93\xa9")	// U+e4e9
#define ICON_FA_EYE oxorany("\xef\x81\xae")	// U+f06e
#define ICON_FA_EYE_DROPPER oxorany("\xef\x87\xbb")	// U+f1fb
#define ICON_FA_EYE_LOW_VISION oxorany("\xef\x8a\xa8")	// U+f2a8
#define ICON_FA_EYE_SLASH oxorany("\xef\x81\xb0")	// U+f070
#define ICON_FA_F oxorany("F")	// U+46
#define ICON_FA_FACE_ANGRY oxorany("\xef\x95\x96")	// U+f556
#define ICON_FA_FACE_DIZZY oxorany("\xef\x95\xa7")	// U+f567
#define ICON_FA_FACE_FLUSHED oxorany("\xef\x95\xb9")	// U+f579
#define ICON_FA_FACE_FROWN oxorany("\xef\x84\x99")	// U+f119
#define ICON_FA_FACE_FROWN_OPEN oxorany("\xef\x95\xba")	// U+f57a
#define ICON_FA_FACE_GRIMACE oxorany("\xef\x95\xbf")	// U+f57f
#define ICON_FA_FACE_GRIN oxorany("\xef\x96\x80")	// U+f580
#define ICON_FA_FACE_GRIN_BEAM oxorany("\xef\x96\x82")	// U+f582
#define ICON_FA_FACE_GRIN_BEAM_SWEAT oxorany("\xef\x96\x83")	// U+f583
#define ICON_FA_FACE_GRIN_HEARTS oxorany("\xef\x96\x84")	// U+f584
#define ICON_FA_FACE_GRIN_SQUINT oxorany("\xef\x96\x85")	// U+f585
#define ICON_FA_FACE_GRIN_SQUINT_TEARS oxorany("\xef\x96\x86")	// U+f586
#define ICON_FA_FACE_GRIN_STARS oxorany("\xef\x96\x87")	// U+f587
#define ICON_FA_FACE_GRIN_TEARS oxorany("\xef\x96\x88")	// U+f588
#define ICON_FA_FACE_GRIN_TONGUE oxorany("\xef\x96\x89")	// U+f589
#define ICON_FA_FACE_GRIN_TONGUE_SQUINT oxorany("\xef\x96\x8a")	// U+f58a
#define ICON_FA_FACE_GRIN_TONGUE_WINK oxorany("\xef\x96\x8b")	// U+f58b
#define ICON_FA_FACE_GRIN_WIDE oxorany("\xef\x96\x81")	// U+f581
#define ICON_FA_FACE_GRIN_WINK oxorany("\xef\x96\x8c")	// U+f58c
#define ICON_FA_FACE_KISS oxorany("\xef\x96\x96")	// U+f596
#define ICON_FA_FACE_KISS_BEAM oxorany("\xef\x96\x97")	// U+f597
#define ICON_FA_FACE_KISS_WINK_HEART oxorany("\xef\x96\x98")	// U+f598
#define ICON_FA_FACE_LAUGH oxorany("\xef\x96\x99")	// U+f599
#define ICON_FA_FACE_LAUGH_BEAM oxorany("\xef\x96\x9a")	// U+f59a
#define ICON_FA_FACE_LAUGH_SQUINT oxorany("\xef\x96\x9b")	// U+f59b
#define ICON_FA_FACE_LAUGH_WINK oxorany("\xef\x96\x9c")	// U+f59c
#define ICON_FA_FACE_MEH oxorany("\xef\x84\x9a")	// U+f11a
#define ICON_FA_FACE_MEH_BLANK oxorany("\xef\x96\xa4")	// U+f5a4
#define ICON_FA_FACE_ROLLING_EYES oxorany("\xef\x96\xa5")	// U+f5a5
#define ICON_FA_FACE_SAD_CRY oxorany("\xef\x96\xb3")	// U+f5b3
#define ICON_FA_FACE_SAD_TEAR oxorany("\xef\x96\xb4")	// U+f5b4
#define ICON_FA_FACE_SMILE oxorany("\xef\x84\x98")	// U+f118
#define ICON_FA_FACE_SMILE_BEAM oxorany("\xef\x96\xb8")	// U+f5b8
#define ICON_FA_FACE_SMILE_WINK oxorany("\xef\x93\x9a")	// U+f4da
#define ICON_FA_FACE_SURPRISE oxorany("\xef\x97\x82")	// U+f5c2
#define ICON_FA_FACE_TIRED oxorany("\xef\x97\x88")	// U+f5c8
#define ICON_FA_FAN oxorany("\xef\xa1\xa3")	// U+f863
#define ICON_FA_FAUCET oxorany("\xee\x80\x85")	// U+e005
#define ICON_FA_FAUCET_DRIP oxorany("\xee\x80\x86")	// U+e006
#define ICON_FA_FAX oxorany("\xef\x86\xac")	// U+f1ac
#define ICON_FA_FEATHER oxorany("\xef\x94\xad")	// U+f52d
#define ICON_FA_FEATHER_POINTED oxorany("\xef\x95\xab")	// U+f56b
#define ICON_FA_FERRY oxorany("\xee\x93\xaa")	// U+e4ea
#define ICON_FA_FILE oxorany("\xef\x85\x9b")	// U+f15b
#define ICON_FA_FILE_ARROW_DOWN oxorany("\xef\x95\xad")	// U+f56d
#define ICON_FA_FILE_ARROW_UP oxorany("\xef\x95\xb4")	// U+f574
#define ICON_FA_FILE_AUDIO oxorany("\xef\x87\x87")	// U+f1c7
#define ICON_FA_FILE_CIRCLE_CHECK oxorany("\xee\x92\x93")	// U+e493
#define ICON_FA_FILE_CIRCLE_EXCLAMATION oxorany("\xee\x93\xab")	// U+e4eb
#define ICON_FA_FILE_CIRCLE_MINUS oxorany("\xee\x93\xad")	// U+e4ed
#define ICON_FA_FILE_CIRCLE_PLUS oxorany("\xee\x93\xae")	// U+e4ee
#define ICON_FA_FILE_CIRCLE_QUESTION oxorany("\xee\x93\xaf")	// U+e4ef
#define ICON_FA_FILE_CIRCLE_XMARK oxorany("\xee\x92\x94")	// U+e494
#define ICON_FA_FILE_CODE oxorany("\xef\x87\x89")	// U+f1c9
#define ICON_FA_FILE_CONTRACT oxorany("\xef\x95\xac")	// U+f56c
#define ICON_FA_FILE_CSV oxorany("\xef\x9b\x9d")	// U+f6dd
#define ICON_FA_FILE_EXCEL oxorany("\xef\x87\x83")	// U+f1c3
#define ICON_FA_FILE_EXPORT oxorany("\xef\x95\xae")	// U+f56e
#define ICON_FA_FILE_IMAGE oxorany("\xef\x87\x85")	// U+f1c5
#define ICON_FA_FILE_IMPORT oxorany("\xef\x95\xaf")	// U+f56f
#define ICON_FA_FILE_INVOICE oxorany("\xef\x95\xb0")	// U+f570
#define ICON_FA_FILE_INVOICE_DOLLAR oxorany("\xef\x95\xb1")	// U+f571
#define ICON_FA_FILE_LINES oxorany("\xef\x85\x9c")	// U+f15c
#define ICON_FA_FILE_MEDICAL oxorany("\xef\x91\xb7")	// U+f477
#define ICON_FA_FILE_PDF oxorany("\xef\x87\x81")	// U+f1c1
#define ICON_FA_FILE_PEN oxorany("\xef\x8c\x9c")	// U+f31c
#define ICON_FA_FILE_POWERPOINT oxorany("\xef\x87\x84")	// U+f1c4
#define ICON_FA_FILE_PRESCRIPTION oxorany("\xef\x95\xb2")	// U+f572
#define ICON_FA_FILE_SHIELD oxorany("\xee\x93\xb0")	// U+e4f0
#define ICON_FA_FILE_SIGNATURE oxorany("\xef\x95\xb3")	// U+f573
#define ICON_FA_FILE_VIDEO oxorany("\xef\x87\x88")	// U+f1c8
#define ICON_FA_FILE_WAVEFORM oxorany("\xef\x91\xb8")	// U+f478
#define ICON_FA_FILE_WORD oxorany("\xef\x87\x82")	// U+f1c2
#define ICON_FA_FILE_ZIPPER oxorany("\xef\x87\x86")	// U+f1c6
#define ICON_FA_FILL oxorany("\xef\x95\xb5")	// U+f575
#define ICON_FA_FILL_DRIP oxorany("\xef\x95\xb6")	// U+f576
#define ICON_FA_FILM oxorany("\xef\x80\x88")	// U+f008
#define ICON_FA_FILTER oxorany("\xef\x82\xb0")	// U+f0b0
#define ICON_FA_FILTER_CIRCLE_DOLLAR oxorany("\xef\x99\xa2")	// U+f662
#define ICON_FA_FILTER_CIRCLE_XMARK oxorany("\xee\x85\xbb")	// U+e17b
#define ICON_FA_FINGERPRINT oxorany("\xef\x95\xb7")	// U+f577
#define ICON_FA_FIRE oxorany("\xef\x81\xad")	// U+f06d
#define ICON_FA_FIRE_BURNER oxorany("\xee\x93\xb1")	// U+e4f1
#define ICON_FA_FIRE_EXTINGUISHER oxorany("\xef\x84\xb4")	// U+f134
#define ICON_FA_FIRE_FLAME_CURVED oxorany("\xef\x9f\xa4")	// U+f7e4
#define ICON_FA_FIRE_FLAME_SIMPLE oxorany("\xef\x91\xaa")	// U+f46a
#define ICON_FA_FISH oxorany("\xef\x95\xb8")	// U+f578
#define ICON_FA_FISH_FINS oxorany("\xee\x93\xb2")	// U+e4f2
#define ICON_FA_FLAG oxorany("\xef\x80\xa4")	// U+f024
#define ICON_FA_FLAG_CHECKERED oxorany("\xef\x84\x9e")	// U+f11e
#define ICON_FA_FLAG_USA oxorany("\xef\x9d\x8d")	// U+f74d
#define ICON_FA_FLASK oxorany("\xef\x83\x83")	// U+f0c3
#define ICON_FA_FLASK_VIAL oxorany("\xee\x93\xb3")	// U+e4f3
#define ICON_FA_FLOPPY_DISK oxorany("\xef\x83\x87")	// U+f0c7
#define ICON_FA_FLORIN_SIGN oxorany("\xee\x86\x84")	// U+e184
#define ICON_FA_FOLDER oxorany("\xef\x81\xbb")	// U+f07b
#define ICON_FA_FOLDER_CLOSED oxorany("\xee\x86\x85")	// U+e185
#define ICON_FA_FOLDER_MINUS oxorany("\xef\x99\x9d")	// U+f65d
#define ICON_FA_FOLDER_OPEN oxorany("\xef\x81\xbc")	// U+f07c
#define ICON_FA_FOLDER_PLUS oxorany("\xef\x99\x9e")	// U+f65e
#define ICON_FA_FOLDER_TREE oxorany("\xef\xa0\x82")	// U+f802
#define ICON_FA_FONT oxorany("\xef\x80\xb1")	// U+f031
#define ICON_FA_FONT_AWESOME oxorany("\xef\x8a\xb4")	// U+f2b4
#define ICON_FA_FOOTBALL oxorany("\xef\x91\x8e")	// U+f44e
#define ICON_FA_FORWARD oxorany("\xef\x81\x8e")	// U+f04e
#define ICON_FA_FORWARD_FAST oxorany("\xef\x81\x90")	// U+f050
#define ICON_FA_FORWARD_STEP oxorany("\xef\x81\x91")	// U+f051
#define ICON_FA_FRANC_SIGN oxorany("\xee\x86\x8f")	// U+e18f
#define ICON_FA_FROG oxorany("\xef\x94\xae")	// U+f52e
#define ICON_FA_FUTBOL oxorany("\xef\x87\xa3")	// U+f1e3
#define ICON_FA_G oxorany("G")	// U+47
#define ICON_FA_GAMEPAD oxorany("\xef\x84\x9b")	// U+f11b
#define ICON_FA_GAS_PUMP oxorany("\xef\x94\xaf")	// U+f52f
#define ICON_FA_GAUGE oxorany("\xef\x98\xa4")	// U+f624
#define ICON_FA_GAUGE_HIGH oxorany("\xef\x98\xa5")	// U+f625
#define ICON_FA_GAUGE_SIMPLE oxorany("\xef\x98\xa9")	// U+f629
#define ICON_FA_GAUGE_SIMPLE_HIGH oxorany("\xef\x98\xaa")	// U+f62a
#define ICON_FA_GAVEL oxorany("\xef\x83\xa3")	// U+f0e3
#define ICON_FA_GEAR oxorany("\xef\x80\x93")	// U+f013
#define ICON_FA_GEARS oxorany("\xef\x82\x85")	// U+f085
#define ICON_FA_GEM oxorany("\xef\x8e\xa5")	// U+f3a5
#define ICON_FA_GENDERLESS oxorany("\xef\x88\xad")	// U+f22d
#define ICON_FA_GHOST oxorany("\xef\x9b\xa2")	// U+f6e2
#define ICON_FA_GIFT oxorany("\xef\x81\xab")	// U+f06b
#define ICON_FA_GIFTS oxorany("\xef\x9e\x9c")	// U+f79c
#define ICON_FA_GLASS_WATER oxorany("\xee\x93\xb4")	// U+e4f4
#define ICON_FA_GLASS_WATER_DROPLET oxorany("\xee\x93\xb5")	// U+e4f5
#define ICON_FA_GLASSES oxorany("\xef\x94\xb0")	// U+f530
#define ICON_FA_GLOBE oxorany("\xef\x82\xac")	// U+f0ac
#define ICON_FA_GOLF_BALL_TEE oxorany("\xef\x91\x90")	// U+f450
#define ICON_FA_GOPURAM oxorany("\xef\x99\xa4")	// U+f664
#define ICON_FA_GRADUATION_CAP oxorany("\xef\x86\x9d")	// U+f19d
#define ICON_FA_GREATER_THAN oxorany(">")	// U+3e
#define ICON_FA_GREATER_THAN_EQUAL oxorany("\xef\x94\xb2")	// U+f532
#define ICON_FA_GRIP oxorany("\xef\x96\x8d")	// U+f58d
#define ICON_FA_GRIP_LINES oxorany("\xef\x9e\xa4")	// U+f7a4
#define ICON_FA_GRIP_LINES_VERTICAL oxorany("\xef\x9e\xa5")	// U+f7a5
#define ICON_FA_GRIP_VERTICAL oxorany("\xef\x96\x8e")	// U+f58e
#define ICON_FA_GROUP_ARROWS_ROTATE oxorany("\xee\x93\xb6")	// U+e4f6
#define ICON_FA_GUARANI_SIGN oxorany("\xee\x86\x9a")	// U+e19a
#define ICON_FA_GUITAR oxorany("\xef\x9e\xa6")	// U+f7a6
#define ICON_FA_GUN oxorany("\xee\x86\x9b")	// U+e19b
#define ICON_FA_H oxorany("H")	// U+48
#define ICON_FA_HAMMER oxorany("\xef\x9b\xa3")	// U+f6e3
#define ICON_FA_HAMSA oxorany("\xef\x99\xa5")	// U+f665
#define ICON_FA_HAND oxorany("\xef\x89\x96")	// U+f256
#define ICON_FA_HAND_BACK_FIST oxorany("\xef\x89\x95")	// U+f255
#define ICON_FA_HAND_DOTS oxorany("\xef\x91\xa1")	// U+f461
#define ICON_FA_HAND_FIST oxorany("\xef\x9b\x9e")	// U+f6de
#define ICON_FA_HAND_HOLDING oxorany("\xef\x92\xbd")	// U+f4bd
#define ICON_FA_HAND_HOLDING_DOLLAR oxorany("\xef\x93\x80")	// U+f4c0
#define ICON_FA_HAND_HOLDING_DROPLET oxorany("\xef\x93\x81")	// U+f4c1
#define ICON_FA_HAND_HOLDING_HAND oxorany("\xee\x93\xb7")	// U+e4f7
#define ICON_FA_HAND_HOLDING_HEART oxorany("\xef\x92\xbe")	// U+f4be
#define ICON_FA_HAND_HOLDING_MEDICAL oxorany("\xee\x81\x9c")	// U+e05c
#define ICON_FA_HAND_LIZARD oxorany("\xef\x89\x98")	// U+f258
#define ICON_FA_HAND_MIDDLE_FINGER oxorany("\xef\xa0\x86")	// U+f806
#define ICON_FA_HAND_PEACE oxorany("\xef\x89\x9b")	// U+f25b
#define ICON_FA_HAND_POINT_DOWN oxorany("\xef\x82\xa7")	// U+f0a7
#define ICON_FA_HAND_POINT_LEFT oxorany("\xef\x82\xa5")	// U+f0a5
#define ICON_FA_HAND_POINT_RIGHT oxorany("\xef\x82\xa4")	// U+f0a4
#define ICON_FA_HAND_POINT_UP oxorany("\xef\x82\xa6")	// U+f0a6
#define ICON_FA_HAND_POINTER oxorany("\xef\x89\x9a")	// U+f25a
#define ICON_FA_HAND_SCISSORS oxorany("\xef\x89\x97")	// U+f257
#define ICON_FA_HAND_SPARKLES oxorany("\xee\x81\x9d")	// U+e05d
#define ICON_FA_HAND_SPOCK oxorany("\xef\x89\x99")	// U+f259
#define ICON_FA_HANDCUFFS oxorany("\xee\x93\xb8")	// U+e4f8
#define ICON_FA_HANDS oxorany("\xef\x8a\xa7")	// U+f2a7
#define ICON_FA_HANDS_ASL_INTERPRETING oxorany("\xef\x8a\xa3")	// U+f2a3
#define ICON_FA_HANDS_BOUND oxorany("\xee\x93\xb9")	// U+e4f9
#define ICON_FA_HANDS_BUBBLES oxorany("\xee\x81\x9e")	// U+e05e
#define ICON_FA_HANDS_CLAPPING oxorany("\xee\x86\xa8")	// U+e1a8
#define ICON_FA_HANDS_HOLDING oxorany("\xef\x93\x82")	// U+f4c2
#define ICON_FA_HANDS_HOLDING_CHILD oxorany("\xee\x93\xba")	// U+e4fa
#define ICON_FA_HANDS_HOLDING_CIRCLE oxorany("\xee\x93\xbb")	// U+e4fb
#define ICON_FA_HANDS_PRAYING oxorany("\xef\x9a\x84")	// U+f684
#define ICON_FA_HANDSHAKE oxorany("\xef\x8a\xb5")	// U+f2b5
#define ICON_FA_HANDSHAKE_ANGLE oxorany("\xef\x93\x84")	// U+f4c4
#define ICON_FA_HANDSHAKE_SIMPLE oxorany("\xef\x93\x86")	// U+f4c6
#define ICON_FA_HANDSHAKE_SIMPLE_SLASH oxorany("\xee\x81\x9f")	// U+e05f
#define ICON_FA_HANDSHAKE_SLASH oxorany("\xee\x81\xa0")	// U+e060
#define ICON_FA_HANUKIAH oxorany("\xef\x9b\xa6")	// U+f6e6
#define ICON_FA_HARD_DRIVE oxorany("\xef\x82\xa0")	// U+f0a0
#define ICON_FA_HASHTAG oxorany("#")	// U+23
#define ICON_FA_HAT_COWBOY oxorany("\xef\xa3\x80")	// U+f8c0
#define ICON_FA_HAT_COWBOY_SIDE oxorany("\xef\xa3\x81")	// U+f8c1
#define ICON_FA_HAT_WIZARD oxorany("\xef\x9b\xa8")	// U+f6e8
#define ICON_FA_HEAD_SIDE_COUGH oxorany("\xee\x81\xa1")	// U+e061
#define ICON_FA_HEAD_SIDE_COUGH_SLASH oxorany("\xee\x81\xa2")	// U+e062
#define ICON_FA_HEAD_SIDE_MASK oxorany("\xee\x81\xa3")	// U+e063
#define ICON_FA_HEAD_SIDE_VIRUS oxorany("\xee\x81\xa4")	// U+e064
#define ICON_FA_HEADING oxorany("\xef\x87\x9c")	// U+f1dc
#define ICON_FA_HEADPHONES oxorany("\xef\x80\xa5")	// U+f025
#define ICON_FA_HEADPHONES_SIMPLE oxorany("\xef\x96\x8f")	// U+f58f
#define ICON_FA_HEADSET oxorany("\xef\x96\x90")	// U+f590
#define ICON_FA_HEART oxorany("\xef\x80\x84")	// U+f004
#define ICON_FA_HEART_CIRCLE_BOLT oxorany("\xee\x93\xbc")	// U+e4fc
#define ICON_FA_HEART_CIRCLE_CHECK oxorany("\xee\x93\xbd")	// U+e4fd
#define ICON_FA_HEART_CIRCLE_EXCLAMATION oxorany("\xee\x93\xbe")	// U+e4fe
#define ICON_FA_HEART_CIRCLE_MINUS oxorany("\xee\x93\xbf")	// U+e4ff
#define ICON_FA_HEART_CIRCLE_PLUS oxorany("\xee\x94\x80")	// U+e500
#define ICON_FA_HEART_CIRCLE_XMARK oxorany("\xee\x94\x81")	// U+e501
#define ICON_FA_HEART_CRACK oxorany("\xef\x9e\xa9")	// U+f7a9
#define ICON_FA_HEART_PULSE oxorany("\xef\x88\x9e")	// U+f21e
#define ICON_FA_HELICOPTER oxorany("\xef\x94\xb3")	// U+f533
#define ICON_FA_HELICOPTER_SYMBOL oxorany("\xee\x94\x82")	// U+e502
#define ICON_FA_HELMET_SAFETY oxorany("\xef\xa0\x87")	// U+f807
#define ICON_FA_HELMET_UN oxorany("\xee\x94\x83")	// U+e503
#define ICON_FA_HIGHLIGHTER oxorany("\xef\x96\x91")	// U+f591
#define ICON_FA_HILL_AVALANCHE oxorany("\xee\x94\x87")	// U+e507
#define ICON_FA_HILL_ROCKSLIDE oxorany("\xee\x94\x88")	// U+e508
#define ICON_FA_HIPPO oxorany("\xef\x9b\xad")	// U+f6ed
#define ICON_FA_HOCKEY_PUCK oxorany("\xef\x91\x93")	// U+f453
#define ICON_FA_HOLLY_BERRY oxorany("\xef\x9e\xaa")	// U+f7aa
#define ICON_FA_HORSE oxorany("\xef\x9b\xb0")	// U+f6f0
#define ICON_FA_HORSE_HEAD oxorany("\xef\x9e\xab")	// U+f7ab
#define ICON_FA_HOSPITAL oxorany("\xef\x83\xb8")	// U+f0f8
#define ICON_FA_HOSPITAL_USER oxorany("\xef\xa0\x8d")	// U+f80d
#define ICON_FA_HOT_TUB_PERSON oxorany("\xef\x96\x93")	// U+f593
#define ICON_FA_HOTDOG oxorany("\xef\xa0\x8f")	// U+f80f
#define ICON_FA_HOTEL oxorany("\xef\x96\x94")	// U+f594
#define ICON_FA_HOURGLASS oxorany("\xef\x89\x94")	// U+f254
#define ICON_FA_HOURGLASS_EMPTY oxorany("\xef\x89\x92")	// U+f252
#define ICON_FA_HOURGLASS_END oxorany("\xef\x89\x93")	// U+f253
#define ICON_FA_HOURGLASS_START oxorany("\xef\x89\x91")	// U+f251
#define ICON_FA_HOUSE oxorany("\xef\x80\x95")	// U+f015
#define ICON_FA_HOUSE_CHIMNEY oxorany("\xee\x8e\xaf")	// U+e3af
#define ICON_FA_HOUSE_CHIMNEY_CRACK oxorany("\xef\x9b\xb1")	// U+f6f1
#define ICON_FA_HOUSE_CHIMNEY_MEDICAL oxorany("\xef\x9f\xb2")	// U+f7f2
#define ICON_FA_HOUSE_CHIMNEY_USER oxorany("\xee\x81\xa5")	// U+e065
#define ICON_FA_HOUSE_CHIMNEY_WINDOW oxorany("\xee\x80\x8d")	// U+e00d
#define ICON_FA_HOUSE_CIRCLE_CHECK oxorany("\xee\x94\x89")	// U+e509
#define ICON_FA_HOUSE_CIRCLE_EXCLAMATION oxorany("\xee\x94\x8a")	// U+e50a
#define ICON_FA_HOUSE_CIRCLE_XMARK oxorany("\xee\x94\x8b")	// U+e50b
#define ICON_FA_HOUSE_CRACK oxorany("\xee\x8e\xb1")	// U+e3b1
#define ICON_FA_HOUSE_FIRE oxorany("\xee\x94\x8c")	// U+e50c
#define ICON_FA_HOUSE_FLAG oxorany("\xee\x94\x8d")	// U+e50d
#define ICON_FA_HOUSE_FLOOD_WATER oxorany("\xee\x94\x8e")	// U+e50e
#define ICON_FA_HOUSE_FLOOD_WATER_CIRCLE_ARROW_RIGHT oxorany("\xee\x94\x8f")	// U+e50f
#define ICON_FA_HOUSE_LAPTOP oxorany("\xee\x81\xa6")	// U+e066
#define ICON_FA_HOUSE_LOCK oxorany("\xee\x94\x90")	// U+e510
#define ICON_FA_HOUSE_MEDICAL oxorany("\xee\x8e\xb2")	// U+e3b2
#define ICON_FA_HOUSE_MEDICAL_CIRCLE_CHECK oxorany("\xee\x94\x91")	// U+e511
#define ICON_FA_HOUSE_MEDICAL_CIRCLE_EXCLAMATION oxorany("\xee\x94\x92")	// U+e512
#define ICON_FA_HOUSE_MEDICAL_CIRCLE_XMARK oxorany("\xee\x94\x93")	// U+e513
#define ICON_FA_HOUSE_MEDICAL_FLAG oxorany("\xee\x94\x94")	// U+e514
#define ICON_FA_HOUSE_SIGNAL oxorany("\xee\x80\x92")	// U+e012
#define ICON_FA_HOUSE_TSUNAMI oxorany("\xee\x94\x95")	// U+e515
#define ICON_FA_HOUSE_USER oxorany("\xee\x86\xb0")	// U+e1b0
#define ICON_FA_HRYVNIA_SIGN oxorany("\xef\x9b\xb2")	// U+f6f2
#define ICON_FA_HURRICANE oxorany("\xef\x9d\x91")	// U+f751
#define ICON_FA_I oxorany("I")	// U+49
#define ICON_FA_I_CURSOR oxorany("\xef\x89\x86")	// U+f246
#define ICON_FA_ICE_CREAM oxorany("\xef\xa0\x90")	// U+f810
#define ICON_FA_ICICLES oxorany("\xef\x9e\xad")	// U+f7ad
#define ICON_FA_ICONS oxorany("\xef\xa1\xad")	// U+f86d
#define ICON_FA_ID_BADGE oxorany("\xef\x8b\x81")	// U+f2c1
#define ICON_FA_ID_CARD oxorany("\xef\x8b\x82")	// U+f2c2
#define ICON_FA_ID_CARD_CLIP oxorany("\xef\x91\xbf")	// U+f47f
#define ICON_FA_IGLOO oxorany("\xef\x9e\xae")	// U+f7ae
#define ICON_FA_IMAGE oxorany("\xef\x80\xbe")	// U+f03e
#define ICON_FA_IMAGE_PORTRAIT oxorany("\xef\x8f\xa0")	// U+f3e0
#define ICON_FA_IMAGES oxorany("\xef\x8c\x82")	// U+f302
#define ICON_FA_INBOX oxorany("\xef\x80\x9c")	// U+f01c
#define ICON_FA_INDENT oxorany("\xef\x80\xbc")	// U+f03c
#define ICON_FA_INDIAN_RUPEE_SIGN oxorany("\xee\x86\xbc")	// U+e1bc
#define ICON_FA_INDUSTRY oxorany("\xef\x89\xb5")	// U+f275
#define ICON_FA_INFINITY oxorany("\xef\x94\xb4")	// U+f534
#define ICON_FA_INFO oxorany("\xef\x84\xa9")	// U+f129
#define ICON_FA_ITALIC oxorany("\xef\x80\xb3")	// U+f033
#define ICON_FA_J oxorany("J")	// U+4a
#define ICON_FA_JAR oxorany("\xee\x94\x96")	// U+e516
#define ICON_FA_JAR_WHEAT oxorany("\xee\x94\x97")	// U+e517
#define ICON_FA_JEDI oxorany("\xef\x99\xa9")	// U+f669
#define ICON_FA_JET_FIGHTER oxorany("\xef\x83\xbb")	// U+f0fb
#define ICON_FA_JET_FIGHTER_UP oxorany("\xee\x94\x98")	// U+e518
#define ICON_FA_JOINT oxorany("\xef\x96\x95")	// U+f595
#define ICON_FA_JUG_DETERGENT oxorany("\xee\x94\x99")	// U+e519
#define ICON_FA_K oxorany("K")	// U+4b
#define ICON_FA_KAABA oxorany("\xef\x99\xab")	// U+f66b
#define ICON_FA_KEY oxorany("\xef\x82\x84")	// U+f084
#define ICON_FA_KEYBOARD oxorany("\xef\x84\x9c")	// U+f11c
#define ICON_FA_KHANDA oxorany("\xef\x99\xad")	// U+f66d
#define ICON_FA_KIP_SIGN oxorany("\xee\x87\x84")	// U+e1c4
#define ICON_FA_KIT_MEDICAL oxorany("\xef\x91\xb9")	// U+f479
#define ICON_FA_KITCHEN_SET oxorany("\xee\x94\x9a")	// U+e51a
#define ICON_FA_KIWI_BIRD oxorany("\xef\x94\xb5")	// U+f535
#define ICON_FA_L oxorany("L")	// U+4c
#define ICON_FA_LAND_MINE_ON oxorany("\xee\x94\x9b")	// U+e51b
#define ICON_FA_LANDMARK oxorany("\xef\x99\xaf")	// U+f66f
#define ICON_FA_LANDMARK_DOME oxorany("\xef\x9d\x92")	// U+f752
#define ICON_FA_LANDMARK_FLAG oxorany("\xee\x94\x9c")	// U+e51c
#define ICON_FA_LANGUAGE oxorany("\xef\x86\xab")	// U+f1ab
#define ICON_FA_LAPTOP oxorany("\xef\x84\x89")	// U+f109
#define ICON_FA_LAPTOP_CODE oxorany("\xef\x97\xbc")	// U+f5fc
#define ICON_FA_LAPTOP_FILE oxorany("\xee\x94\x9d")	// U+e51d
#define ICON_FA_LAPTOP_MEDICAL oxorany("\xef\xa0\x92")	// U+f812
#define ICON_FA_LARI_SIGN oxorany("\xee\x87\x88")	// U+e1c8
#define ICON_FA_LAYER_GROUP oxorany("\xef\x97\xbd")	// U+f5fd
#define ICON_FA_LEAF oxorany("\xef\x81\xac")	// U+f06c
#define ICON_FA_LEFT_LONG oxorany("\xef\x8c\x8a")	// U+f30a
#define ICON_FA_LEFT_RIGHT oxorany("\xef\x8c\xb7")	// U+f337
#define ICON_FA_LEMON oxorany("\xef\x82\x94")	// U+f094
#define ICON_FA_LESS_THAN oxorany("<")	// U+3c
#define ICON_FA_LESS_THAN_EQUAL oxorany("\xef\x94\xb7")	// U+f537
#define ICON_FA_LIFE_RING oxorany("\xef\x87\x8d")	// U+f1cd
#define ICON_FA_LIGHTBULB oxorany("\xef\x83\xab")	// U+f0eb
#define ICON_FA_LINES_LEANING oxorany("\xee\x94\x9e")	// U+e51e
#define ICON_FA_LINK oxorany("\xef\x83\x81")	// U+f0c1
#define ICON_FA_LINK_SLASH oxorany("\xef\x84\xa7")	// U+f127
#define ICON_FA_LIRA_SIGN oxorany("\xef\x86\x95")	// U+f195
#define ICON_FA_LIST oxorany("\xef\x80\xba")	// U+f03a
#define ICON_FA_LIST_CHECK oxorany("\xef\x82\xae")	// U+f0ae
#define ICON_FA_LIST_OL oxorany("\xef\x83\x8b")	// U+f0cb
#define ICON_FA_LIST_UL oxorany("\xef\x83\x8a")	// U+f0ca
#define ICON_FA_LITECOIN_SIGN oxorany("\xee\x87\x93")	// U+e1d3
#define ICON_FA_LOCATION_ARROW oxorany("\xef\x84\xa4")	// U+f124
#define ICON_FA_LOCATION_CROSSHAIRS oxorany("\xef\x98\x81")	// U+f601
#define ICON_FA_LOCATION_DOT oxorany("\xef\x8f\x85")	// U+f3c5
#define ICON_FA_LOCATION_PIN oxorany("\xef\x81\x81")	// U+f041
#define ICON_FA_LOCATION_PIN_LOCK oxorany("\xee\x94\x9f")	// U+e51f
#define ICON_FA_LOCK oxorany("\xef\x80\xa3")	// U+f023
#define ICON_FA_LOCK_OPEN oxorany("\xef\x8f\x81")	// U+f3c1
#define ICON_FA_LOCUST oxorany("\xee\x94\xa0")	// U+e520
#define ICON_FA_LUNGS oxorany("\xef\x98\x84")	// U+f604
#define ICON_FA_LUNGS_VIRUS oxorany("\xee\x81\xa7")	// U+e067
#define ICON_FA_M oxorany("M")	// U+4d
#define ICON_FA_MAGNET oxorany("\xef\x81\xb6")	// U+f076
#define ICON_FA_MAGNIFYING_GLASS oxorany("\xef\x80\x82")	// U+f002
#define ICON_FA_MAGNIFYING_GLASS_ARROW_RIGHT oxorany("\xee\x94\xa1")	// U+e521
#define ICON_FA_MAGNIFYING_GLASS_CHART oxorany("\xee\x94\xa2")	// U+e522
#define ICON_FA_MAGNIFYING_GLASS_DOLLAR oxorany("\xef\x9a\x88")	// U+f688
#define ICON_FA_MAGNIFYING_GLASS_LOCATION oxorany("\xef\x9a\x89")	// U+f689
#define ICON_FA_MAGNIFYING_GLASS_MINUS oxorany("\xef\x80\x90")	// U+f010
#define ICON_FA_MAGNIFYING_GLASS_PLUS oxorany("\xef\x80\x8e")	// U+f00e
#define ICON_FA_MANAT_SIGN oxorany("\xee\x87\x95")	// U+e1d5
#define ICON_FA_MAP oxorany("\xef\x89\xb9")	// U+f279
#define ICON_FA_MAP_LOCATION oxorany("\xef\x96\x9f")	// U+f59f
#define ICON_FA_MAP_LOCATION_DOT oxorany("\xef\x96\xa0")	// U+f5a0
#define ICON_FA_MAP_PIN oxorany("\xef\x89\xb6")	// U+f276
#define ICON_FA_MARKER oxorany("\xef\x96\xa1")	// U+f5a1
#define ICON_FA_MARS oxorany("\xef\x88\xa2")	// U+f222
#define ICON_FA_MARS_AND_VENUS oxorany("\xef\x88\xa4")	// U+f224
#define ICON_FA_MARS_AND_VENUS_BURST oxorany("\xee\x94\xa3")	// U+e523
#define ICON_FA_MARS_DOUBLE oxorany("\xef\x88\xa7")	// U+f227
#define ICON_FA_MARS_STROKE oxorany("\xef\x88\xa9")	// U+f229
#define ICON_FA_MARS_STROKE_RIGHT oxorany("\xef\x88\xab")	// U+f22b
#define ICON_FA_MARS_STROKE_UP oxorany("\xef\x88\xaa")	// U+f22a
#define ICON_FA_MARTINI_GLASS oxorany("\xef\x95\xbb")	// U+f57b
#define ICON_FA_MARTINI_GLASS_CITRUS oxorany("\xef\x95\xa1")	// U+f561
#define ICON_FA_MARTINI_GLASS_EMPTY oxorany("\xef\x80\x80")	// U+f000
#define ICON_FA_MASK oxorany("\xef\x9b\xba")	// U+f6fa
#define ICON_FA_MASK_FACE oxorany("\xee\x87\x97")	// U+e1d7
#define ICON_FA_MASK_VENTILATOR oxorany("\xee\x94\xa4")	// U+e524
#define ICON_FA_MASKS_THEATER oxorany("\xef\x98\xb0")	// U+f630
#define ICON_FA_MATTRESS_PILLOW oxorany("\xee\x94\xa5")	// U+e525
#define ICON_FA_MAXIMIZE oxorany("\xef\x8c\x9e")	// U+f31e
#define ICON_FA_MEDAL oxorany("\xef\x96\xa2")	// U+f5a2
#define ICON_FA_MEMORY oxorany("\xef\x94\xb8")	// U+f538
#define ICON_FA_MENORAH oxorany("\xef\x99\xb6")	// U+f676
#define ICON_FA_MERCURY oxorany("\xef\x88\xa3")	// U+f223
#define ICON_FA_MESSAGE oxorany("\xef\x89\xba")	// U+f27a
#define ICON_FA_METEOR oxorany("\xef\x9d\x93")	// U+f753
#define ICON_FA_MICROCHIP oxorany("\xef\x8b\x9b")	// U+f2db
#define ICON_FA_MICROPHONE oxorany("\xef\x84\xb0")	// U+f130
#define ICON_FA_MICROPHONE_LINES oxorany("\xef\x8f\x89")	// U+f3c9
#define ICON_FA_MICROPHONE_LINES_SLASH oxorany("\xef\x94\xb9")	// U+f539
#define ICON_FA_MICROPHONE_SLASH oxorany("\xef\x84\xb1")	// U+f131
#define ICON_FA_MICROSCOPE oxorany("\xef\x98\x90")	// U+f610
#define ICON_FA_MILL_SIGN oxorany("\xee\x87\xad")	// U+e1ed
#define ICON_FA_MINIMIZE oxorany("\xef\x9e\x8c")	// U+f78c
#define ICON_FA_MINUS oxorany("\xef\x81\xa8")	// U+f068
#define ICON_FA_MITTEN oxorany("\xef\x9e\xb5")	// U+f7b5
#define ICON_FA_MOBILE oxorany("\xef\x8f\x8e")	// U+f3ce
#define ICON_FA_MOBILE_BUTTON oxorany("\xef\x84\x8b")	// U+f10b
#define ICON_FA_MOBILE_RETRO oxorany("\xee\x94\xa7")	// U+e527
#define ICON_FA_MOBILE_SCREEN oxorany("\xef\x8f\x8f")	// U+f3cf
#define ICON_FA_MOBILE_SCREEN_BUTTON oxorany("\xef\x8f\x8d")	// U+f3cd
#define ICON_FA_MONEY_BILL oxorany("\xef\x83\x96")	// U+f0d6
#define ICON_FA_MONEY_BILL_1 oxorany("\xef\x8f\x91")	// U+f3d1
#define ICON_FA_MONEY_BILL_1_WAVE oxorany("\xef\x94\xbb")	// U+f53b
#define ICON_FA_MONEY_BILL_TRANSFER oxorany("\xee\x94\xa8")	// U+e528
#define ICON_FA_MONEY_BILL_TREND_UP oxorany("\xee\x94\xa9")	// U+e529
#define ICON_FA_MONEY_BILL_WAVE oxorany("\xef\x94\xba")	// U+f53a
#define ICON_FA_MONEY_BILL_WHEAT oxorany("\xee\x94\xaa")	// U+e52a
#define ICON_FA_MONEY_BILLS oxorany("\xee\x87\xb3")	// U+e1f3
#define ICON_FA_MONEY_CHECK oxorany("\xef\x94\xbc")	// U+f53c
#define ICON_FA_MONEY_CHECK_DOLLAR oxorany("\xef\x94\xbd")	// U+f53d
#define ICON_FA_MONUMENT oxorany("\xef\x96\xa6")	// U+f5a6
#define ICON_FA_MOON oxorany("\xef\x86\x86")	// U+f186
#define ICON_FA_MORTAR_PESTLE oxorany("\xef\x96\xa7")	// U+f5a7
#define ICON_FA_MOSQUE oxorany("\xef\x99\xb8")	// U+f678
#define ICON_FA_MOSQUITO oxorany("\xee\x94\xab")	// U+e52b
#define ICON_FA_MOSQUITO_NET oxorany("\xee\x94\xac")	// U+e52c
#define ICON_FA_MOTORCYCLE oxorany("\xef\x88\x9c")	// U+f21c
#define ICON_FA_MOUND oxorany("\xee\x94\xad")	// U+e52d
#define ICON_FA_MOUNTAIN oxorany("\xef\x9b\xbc")	// U+f6fc
#define ICON_FA_MOUNTAIN_CITY oxorany("\xee\x94\xae")	// U+e52e
#define ICON_FA_MOUNTAIN_SUN oxorany("\xee\x94\xaf")	// U+e52f
#define ICON_FA_MUG_HOT oxorany("\xef\x9e\xb6")	// U+f7b6
#define ICON_FA_MUG_SAUCER oxorany("\xef\x83\xb4")	// U+f0f4
#define ICON_FA_MUSIC oxorany("\xef\x80\x81")	// U+f001
#define ICON_FA_N oxorany("N")	// U+4e
#define ICON_FA_NAIRA_SIGN oxorany("\xee\x87\xb6")	// U+e1f6
#define ICON_FA_NETWORK_WIRED oxorany("\xef\x9b\xbf")	// U+f6ff
#define ICON_FA_NEUTER oxorany("\xef\x88\xac")	// U+f22c
#define ICON_FA_NEWSPAPER oxorany("\xef\x87\xaa")	// U+f1ea
#define ICON_FA_NOT_EQUAL oxorany("\xef\x94\xbe")	// U+f53e
#define ICON_FA_NOTE_STICKY oxorany("\xef\x89\x89")	// U+f249
#define ICON_FA_NOTES_MEDICAL oxorany("\xef\x92\x81")	// U+f481
#define ICON_FA_O oxorany("O")	// U+4f
#define ICON_FA_OBJECT_GROUP oxorany("\xef\x89\x87")	// U+f247
#define ICON_FA_OBJECT_UNGROUP oxorany("\xef\x89\x88")	// U+f248
#define ICON_FA_OIL_CAN oxorany("\xef\x98\x93")	// U+f613
#define ICON_FA_OIL_WELL oxorany("\xee\x94\xb2")	// U+e532
#define ICON_FA_OM oxorany("\xef\x99\xb9")	// U+f679
#define ICON_FA_OTTER oxorany("\xef\x9c\x80")	// U+f700
#define ICON_FA_OUTDENT oxorany("\xef\x80\xbb")	// U+f03b
#define ICON_FA_P oxorany("P")	// U+50
#define ICON_FA_PAGER oxorany("\xef\xa0\x95")	// U+f815
#define ICON_FA_PAINT_ROLLER oxorany("\xef\x96\xaa")	// U+f5aa
#define ICON_FA_PAINTBRUSH oxorany("\xef\x87\xbc")	// U+f1fc
#define ICON_FA_PALETTE oxorany("\xef\x94\xbf")	// U+f53f
#define ICON_FA_PALLET oxorany("\xef\x92\x82")	// U+f482
#define ICON_FA_PANORAMA oxorany("\xee\x88\x89")	// U+e209
#define ICON_FA_PAPER_PLANE oxorany("\xef\x87\x98")	// U+f1d8
#define ICON_FA_PAPERCLIP oxorany("\xef\x83\x86")	// U+f0c6
#define ICON_FA_PARACHUTE_BOX oxorany("\xef\x93\x8d")	// U+f4cd
#define ICON_FA_PARAGRAPH oxorany("\xef\x87\x9d")	// U+f1dd
#define ICON_FA_PASSPORT oxorany("\xef\x96\xab")	// U+f5ab
#define ICON_FA_PASTE oxorany("\xef\x83\xaa")	// U+f0ea
#define ICON_FA_PAUSE oxorany("\xef\x81\x8c")	// U+f04c
#define ICON_FA_PAW oxorany("\xef\x86\xb0")	// U+f1b0
#define ICON_FA_PEACE oxorany("\xef\x99\xbc")	// U+f67c
#define ICON_FA_PEN oxorany("\xef\x8c\x84")	// U+f304
#define ICON_FA_PEN_CLIP oxorany("\xef\x8c\x85")	// U+f305
#define ICON_FA_PEN_FANCY oxorany("\xef\x96\xac")	// U+f5ac
#define ICON_FA_PEN_NIB oxorany("\xef\x96\xad")	// U+f5ad
#define ICON_FA_PEN_RULER oxorany("\xef\x96\xae")	// U+f5ae
#define ICON_FA_PEN_TO_SQUARE oxorany("\xef\x81\x84")	// U+f044
#define ICON_FA_PENCIL oxorany("\xef\x8c\x83")	// U+f303
#define ICON_FA_PEOPLE_ARROWS_LEFT_RIGHT oxorany("\xee\x81\xa8")	// U+e068
#define ICON_FA_PEOPLE_CARRY_BOX oxorany("\xef\x93\x8e")	// U+f4ce
#define ICON_FA_PEOPLE_GROUP oxorany("\xee\x94\xb3")	// U+e533
#define ICON_FA_PEOPLE_LINE oxorany("\xee\x94\xb4")	// U+e534
#define ICON_FA_PEOPLE_PULLING oxorany("\xee\x94\xb5")	// U+e535
#define ICON_FA_PEOPLE_ROBBERY oxorany("\xee\x94\xb6")	// U+e536
#define ICON_FA_PEOPLE_ROOF oxorany("\xee\x94\xb7")	// U+e537
#define ICON_FA_PEPPER_HOT oxorany("\xef\xa0\x96")	// U+f816
#define ICON_FA_PERCENT oxorany("%")	// U+25
#define ICON_FA_PERSON oxorany("\xef\x86\x83")	// U+f183
#define ICON_FA_PERSON_ARROW_DOWN_TO_LINE oxorany("\xee\x94\xb8")	// U+e538
#define ICON_FA_PERSON_ARROW_UP_FROM_LINE oxorany("\xee\x94\xb9")	// U+e539
#define ICON_FA_PERSON_BIKING oxorany("\xef\xa1\x8a")	// U+f84a
#define ICON_FA_PERSON_BOOTH oxorany("\xef\x9d\x96")	// U+f756
#define ICON_FA_PERSON_BREASTFEEDING oxorany("\xee\x94\xba")	// U+e53a
#define ICON_FA_PERSON_BURST oxorany("\xee\x94\xbb")	// U+e53b
#define ICON_FA_PERSON_CANE oxorany("\xee\x94\xbc")	// U+e53c
#define ICON_FA_PERSON_CHALKBOARD oxorany("\xee\x94\xbd")	// U+e53d
#define ICON_FA_PERSON_CIRCLE_CHECK oxorany("\xee\x94\xbe")	// U+e53e
#define ICON_FA_PERSON_CIRCLE_EXCLAMATION oxorany("\xee\x94\xbf")	// U+e53f
#define ICON_FA_PERSON_CIRCLE_MINUS oxorany("\xee\x95\x80")	// U+e540
#define ICON_FA_PERSON_CIRCLE_PLUS oxorany("\xee\x95\x81")	// U+e541
#define ICON_FA_PERSON_CIRCLE_QUESTION oxorany("\xee\x95\x82")	// U+e542
#define ICON_FA_PERSON_CIRCLE_XMARK oxorany("\xee\x95\x83")	// U+e543
#define ICON_FA_PERSON_DIGGING oxorany("\xef\xa1\x9e")	// U+f85e
#define ICON_FA_PERSON_DOTS_FROM_LINE oxorany("\xef\x91\xb0")	// U+f470
#define ICON_FA_PERSON_DRESS oxorany("\xef\x86\x82")	// U+f182
#define ICON_FA_PERSON_DRESS_BURST oxorany("\xee\x95\x84")	// U+e544
#define ICON_FA_PERSON_DROWNING oxorany("\xee\x95\x85")	// U+e545
#define ICON_FA_PERSON_FALLING oxorany("\xee\x95\x86")	// U+e546
#define ICON_FA_PERSON_FALLING_BURST oxorany("\xee\x95\x87")	// U+e547
#define ICON_FA_PERSON_HALF_DRESS oxorany("\xee\x95\x88")	// U+e548
#define ICON_FA_PERSON_HARASSING oxorany("\xee\x95\x89")	// U+e549
#define ICON_FA_PERSON_HIKING oxorany("\xef\x9b\xac")	// U+f6ec
#define ICON_FA_PERSON_MILITARY_POINTING oxorany("\xee\x95\x8a")	// U+e54a
#define ICON_FA_PERSON_MILITARY_RIFLE oxorany("\xee\x95\x8b")	// U+e54b
#define ICON_FA_PERSON_MILITARY_TO_PERSON oxorany("\xee\x95\x8c")	// U+e54c
#define ICON_FA_PERSON_PRAYING oxorany("\xef\x9a\x83")	// U+f683
#define ICON_FA_PERSON_PREGNANT oxorany("\xee\x8c\x9e")	// U+e31e
#define ICON_FA_PERSON_RAYS oxorany("\xee\x95\x8d")	// U+e54d
#define ICON_FA_PERSON_RIFLE oxorany("\xee\x95\x8e")	// U+e54e
#define ICON_FA_PERSON_RUNNING oxorany("\xef\x9c\x8c")	// U+f70c
#define ICON_FA_PERSON_SHELTER oxorany("\xee\x95\x8f")	// U+e54f
#define ICON_FA_PERSON_SKATING oxorany("\xef\x9f\x85")	// U+f7c5
#define ICON_FA_PERSON_SKIING oxorany("\xef\x9f\x89")	// U+f7c9
#define ICON_FA_PERSON_SKIING_NORDIC oxorany("\xef\x9f\x8a")	// U+f7ca
#define ICON_FA_PERSON_SNOWBOARDING oxorany("\xef\x9f\x8e")	// U+f7ce
#define ICON_FA_PERSON_SWIMMING oxorany("\xef\x97\x84")	// U+f5c4
#define ICON_FA_PERSON_THROUGH_WINDOW oxorany("\xee\x90\xb3")	// U+e433
#define ICON_FA_PERSON_WALKING oxorany("\xef\x95\x94")	// U+f554
#define ICON_FA_PERSON_WALKING_ARROW_LOOP_LEFT oxorany("\xee\x95\x91")	// U+e551
#define ICON_FA_PERSON_WALKING_ARROW_RIGHT oxorany("\xee\x95\x92")	// U+e552
#define ICON_FA_PERSON_WALKING_DASHED_LINE_ARROW_RIGHT oxorany("\xee\x95\x93")	// U+e553
#define ICON_FA_PERSON_WALKING_LUGGAGE oxorany("\xee\x95\x94")	// U+e554
#define ICON_FA_PERSON_WALKING_WITH_CANE oxorany("\xef\x8a\x9d")	// U+f29d
#define ICON_FA_PESETA_SIGN oxorany("\xee\x88\xa1")	// U+e221
#define ICON_FA_PESO_SIGN oxorany("\xee\x88\xa2")	// U+e222
#define ICON_FA_PHONE oxorany("\xef\x82\x95")	// U+f095
#define ICON_FA_PHONE_FLIP oxorany("\xef\xa1\xb9")	// U+f879
#define ICON_FA_PHONE_SLASH oxorany("\xef\x8f\x9d")	// U+f3dd
#define ICON_FA_PHONE_VOLUME oxorany("\xef\x8a\xa0")	// U+f2a0
#define ICON_FA_PHOTO_FILM oxorany("\xef\xa1\xbc")	// U+f87c
#define ICON_FA_PIGGY_BANK oxorany("\xef\x93\x93")	// U+f4d3
#define ICON_FA_PILLS oxorany("\xef\x92\x84")	// U+f484
#define ICON_FA_PIZZA_SLICE oxorany("\xef\xa0\x98")	// U+f818
#define ICON_FA_PLACE_OF_WORSHIP oxorany("\xef\x99\xbf")	// U+f67f
#define ICON_FA_PLANE oxorany("\xef\x81\xb2")	// U+f072
#define ICON_FA_PLANE_ARRIVAL oxorany("\xef\x96\xaf")	// U+f5af
#define ICON_FA_PLANE_CIRCLE_CHECK oxorany("\xee\x95\x95")	// U+e555
#define ICON_FA_PLANE_CIRCLE_EXCLAMATION oxorany("\xee\x95\x96")	// U+e556
#define ICON_FA_PLANE_CIRCLE_XMARK oxorany("\xee\x95\x97")	// U+e557
#define ICON_FA_PLANE_DEPARTURE oxorany("\xef\x96\xb0")	// U+f5b0
#define ICON_FA_PLANE_LOCK oxorany("\xee\x95\x98")	// U+e558
#define ICON_FA_PLANE_SLASH oxorany("\xee\x81\xa9")	// U+e069
#define ICON_FA_PLANE_UP oxorany("\xee\x88\xad")	// U+e22d
#define ICON_FA_PLANT_WILT oxorany("\xee\x90\xbb")	// U+e43b
#define ICON_FA_PLATE_WHEAT oxorany("\xee\x95\x9a")	// U+e55a
#define ICON_FA_PLAY oxorany("\xef\x81\x8b")	// U+f04b
#define ICON_FA_PLUG oxorany("\xef\x87\xa6")	// U+f1e6
#define ICON_FA_PLUG_CIRCLE_BOLT oxorany("\xee\x95\x9b")	// U+e55b
#define ICON_FA_PLUG_CIRCLE_CHECK oxorany("\xee\x95\x9c")	// U+e55c
#define ICON_FA_PLUG_CIRCLE_EXCLAMATION oxorany("\xee\x95\x9d")	// U+e55d
#define ICON_FA_PLUG_CIRCLE_MINUS oxorany("\xee\x95\x9e")	// U+e55e
#define ICON_FA_PLUG_CIRCLE_PLUS oxorany("\xee\x95\x9f")	// U+e55f
#define ICON_FA_PLUG_CIRCLE_XMARK oxorany("\xee\x95\xa0")	// U+e560
#define ICON_FA_PLUS oxorany("+")	// U+2b
#define ICON_FA_PLUS_MINUS oxorany("\xee\x90\xbc")	// U+e43c
#define ICON_FA_PODCAST oxorany("\xef\x8b\x8e")	// U+f2ce
#define ICON_FA_POO oxorany("\xef\x8b\xbe")	// U+f2fe
#define ICON_FA_POO_STORM oxorany("\xef\x9d\x9a")	// U+f75a
#define ICON_FA_POOP oxorany("\xef\x98\x99")	// U+f619
#define ICON_FA_POWER_OFF oxorany("\xef\x80\x91")	// U+f011
#define ICON_FA_PRESCRIPTION oxorany("\xef\x96\xb1")	// U+f5b1
#define ICON_FA_PRESCRIPTION_BOTTLE oxorany("\xef\x92\x85")	// U+f485
#define ICON_FA_PRESCRIPTION_BOTTLE_MEDICAL oxorany("\xef\x92\x86")	// U+f486
#define ICON_FA_PRINT oxorany("\xef\x80\xaf")	// U+f02f
#define ICON_FA_PUMP_MEDICAL oxorany("\xee\x81\xaa")	// U+e06a
#define ICON_FA_PUMP_SOAP oxorany("\xee\x81\xab")	// U+e06b
#define ICON_FA_PUZZLE_PIECE oxorany("\xef\x84\xae")	// U+f12e
#define ICON_FA_Q oxorany("Q")	// U+51
#define ICON_FA_QRCODE oxorany("\xef\x80\xa9")	// U+f029
#define ICON_FA_QUESTION oxorany("?")	// U+3f
#define ICON_FA_QUOTE_LEFT oxorany("\xef\x84\x8d")	// U+f10d
#define ICON_FA_QUOTE_RIGHT oxorany("\xef\x84\x8e")	// U+f10e
#define ICON_FA_R oxorany("R")	// U+52
#define ICON_FA_RADIATION oxorany("\xef\x9e\xb9")	// U+f7b9
#define ICON_FA_RADIO oxorany("\xef\xa3\x97")	// U+f8d7
#define ICON_FA_RAINBOW oxorany("\xef\x9d\x9b")	// U+f75b
#define ICON_FA_RANKING_STAR oxorany("\xee\x95\xa1")	// U+e561
#define ICON_FA_RECEIPT oxorany("\xef\x95\x83")	// U+f543
#define ICON_FA_RECORD_VINYL oxorany("\xef\xa3\x99")	// U+f8d9
#define ICON_FA_RECTANGLE_AD oxorany("\xef\x99\x81")	// U+f641
#define ICON_FA_RECTANGLE_LIST oxorany("\xef\x80\xa2")	// U+f022
#define ICON_FA_RECTANGLE_XMARK oxorany("\xef\x90\x90")	// U+f410
#define ICON_FA_RECYCLE oxorany("\xef\x86\xb8")	// U+f1b8
#define ICON_FA_REGISTERED oxorany("\xef\x89\x9d")	// U+f25d
#define ICON_FA_REPEAT oxorany("\xef\x8d\xa3")	// U+f363
#define ICON_FA_REPLY oxorany("\xef\x8f\xa5")	// U+f3e5
#define ICON_FA_REPLY_ALL oxorany("\xef\x84\xa2")	// U+f122
#define ICON_FA_REPUBLICAN oxorany("\xef\x9d\x9e")	// U+f75e
#define ICON_FA_RESTROOM oxorany("\xef\x9e\xbd")	// U+f7bd
#define ICON_FA_RETWEET oxorany("\xef\x81\xb9")	// U+f079
#define ICON_FA_RIBBON oxorany("\xef\x93\x96")	// U+f4d6
#define ICON_FA_RIGHT_FROM_BRACKET oxorany("\xef\x8b\xb5")	// U+f2f5
#define ICON_FA_RIGHT_LEFT oxorany("\xef\x8d\xa2")	// U+f362
#define ICON_FA_RIGHT_LONG oxorany("\xef\x8c\x8b")	// U+f30b
#define ICON_FA_RIGHT_TO_BRACKET oxorany("\xef\x8b\xb6")	// U+f2f6
#define ICON_FA_RING oxorany("\xef\x9c\x8b")	// U+f70b
#define ICON_FA_ROAD oxorany("\xef\x80\x98")	// U+f018
#define ICON_FA_ROAD_BARRIER oxorany("\xee\x95\xa2")	// U+e562
#define ICON_FA_ROAD_BRIDGE oxorany("\xee\x95\xa3")	// U+e563
#define ICON_FA_ROAD_CIRCLE_CHECK oxorany("\xee\x95\xa4")	// U+e564
#define ICON_FA_ROAD_CIRCLE_EXCLAMATION oxorany("\xee\x95\xa5")	// U+e565
#define ICON_FA_ROAD_CIRCLE_XMARK oxorany("\xee\x95\xa6")	// U+e566
#define ICON_FA_ROAD_LOCK oxorany("\xee\x95\xa7")	// U+e567
#define ICON_FA_ROAD_SPIKES oxorany("\xee\x95\xa8")	// U+e568
#define ICON_FA_ROBOT oxorany("\xef\x95\x84")	// U+f544
#define ICON_FA_ROCKET oxorany("\xef\x84\xb5")	// U+f135
#define ICON_FA_ROTATE oxorany("\xef\x8b\xb1")	// U+f2f1
#define ICON_FA_ROTATE_LEFT oxorany("\xef\x8b\xaa")	// U+f2ea
#define ICON_FA_ROTATE_RIGHT oxorany("\xef\x8b\xb9")	// U+f2f9
#define ICON_FA_ROUTE oxorany("\xef\x93\x97")	// U+f4d7
#define ICON_FA_RSS oxorany("\xef\x82\x9e")	// U+f09e
#define ICON_FA_RUBLE_SIGN oxorany("\xef\x85\x98")	// U+f158
#define ICON_FA_RUG oxorany("\xee\x95\xa9")	// U+e569
#define ICON_FA_RULER oxorany("\xef\x95\x85")	// U+f545
#define ICON_FA_RULER_COMBINED oxorany("\xef\x95\x86")	// U+f546
#define ICON_FA_RULER_HORIZONTAL oxorany("\xef\x95\x87")	// U+f547
#define ICON_FA_RULER_VERTICAL oxorany("\xef\x95\x88")	// U+f548
#define ICON_FA_RUPEE_SIGN oxorany("\xef\x85\x96")	// U+f156
#define ICON_FA_RUPIAH_SIGN oxorany("\xee\x88\xbd")	// U+e23d
#define ICON_FA_S oxorany("S")	// U+53
#define ICON_FA_SACK_DOLLAR oxorany("\xef\xa0\x9d")	// U+f81d
#define ICON_FA_SACK_XMARK oxorany("\xee\x95\xaa")	// U+e56a
#define ICON_FA_SAILBOAT oxorany("\xee\x91\x85")	// U+e445
#define ICON_FA_SATELLITE oxorany("\xef\x9e\xbf")	// U+f7bf
#define ICON_FA_SATELLITE_DISH oxorany("\xef\x9f\x80")	// U+f7c0
#define ICON_FA_SCALE_BALANCED oxorany("\xef\x89\x8e")	// U+f24e
#define ICON_FA_SCALE_UNBALANCED oxorany("\xef\x94\x95")	// U+f515
#define ICON_FA_SCALE_UNBALANCED_FLIP oxorany("\xef\x94\x96")	// U+f516
#define ICON_FA_SCHOOL oxorany("\xef\x95\x89")	// U+f549
#define ICON_FA_SCHOOL_CIRCLE_CHECK oxorany("\xee\x95\xab")	// U+e56b
#define ICON_FA_SCHOOL_CIRCLE_EXCLAMATION oxorany("\xee\x95\xac")	// U+e56c
#define ICON_FA_SCHOOL_CIRCLE_XMARK oxorany("\xee\x95\xad")	// U+e56d
#define ICON_FA_SCHOOL_FLAG oxorany("\xee\x95\xae")	// U+e56e
#define ICON_FA_SCHOOL_LOCK oxorany("\xee\x95\xaf")	// U+e56f
#define ICON_FA_SCISSORS oxorany("\xef\x83\x84")	// U+f0c4
#define ICON_FA_SCREWDRIVER oxorany("\xef\x95\x8a")	// U+f54a
#define ICON_FA_SCREWDRIVER_WRENCH oxorany("\xef\x9f\x99")	// U+f7d9
#define ICON_FA_SCROLL oxorany("\xef\x9c\x8e")	// U+f70e
#define ICON_FA_SCROLL_TORAH oxorany("\xef\x9a\xa0")	// U+f6a0
#define ICON_FA_SD_CARD oxorany("\xef\x9f\x82")	// U+f7c2
#define ICON_FA_SECTION oxorany("\xee\x91\x87")	// U+e447
#define ICON_FA_SEEDLING oxorany("\xef\x93\x98")	// U+f4d8
#define ICON_FA_SERVER oxorany("\xef\x88\xb3")	// U+f233
#define ICON_FA_SHAPES oxorany("\xef\x98\x9f")	// U+f61f
#define ICON_FA_SHARE oxorany("\xef\x81\xa4")	// U+f064
#define ICON_FA_SHARE_FROM_SQUARE oxorany("\xef\x85\x8d")	// U+f14d
#define ICON_FA_SHARE_NODES oxorany("\xef\x87\xa0")	// U+f1e0
#define ICON_FA_SHEET_PLASTIC oxorany("\xee\x95\xb1")	// U+e571
#define ICON_FA_SHEKEL_SIGN oxorany("\xef\x88\x8b")	// U+f20b
#define ICON_FA_SHIELD oxorany("\xef\x84\xb2")	// U+f132
#define ICON_FA_SHIELD_CAT oxorany("\xee\x95\xb2")	// U+e572
#define ICON_FA_SHIELD_DOG oxorany("\xee\x95\xb3")	// U+e573
#define ICON_FA_SHIELD_HALVED oxorany("\xef\x8f\xad")	// U+f3ed
#define ICON_FA_SHIELD_HEART oxorany("\xee\x95\xb4")	// U+e574
#define ICON_FA_SHIELD_VIRUS oxorany("\xee\x81\xac")	// U+e06c
#define ICON_FA_SHIP oxorany("\xef\x88\x9a")	// U+f21a
#define ICON_FA_SHIRT oxorany("\xef\x95\x93")	// U+f553
#define ICON_FA_SHOE_PRINTS oxorany("\xef\x95\x8b")	// U+f54b
#define ICON_FA_SHOP oxorany("\xef\x95\x8f")	// U+f54f
#define ICON_FA_SHOP_LOCK oxorany("\xee\x92\xa5")	// U+e4a5
#define ICON_FA_SHOP_SLASH oxorany("\xee\x81\xb0")	// U+e070
#define ICON_FA_SHOWER oxorany("\xef\x8b\x8c")	// U+f2cc
#define ICON_FA_SHRIMP oxorany("\xee\x91\x88")	// U+e448
#define ICON_FA_SHUFFLE oxorany("\xef\x81\xb4")	// U+f074
#define ICON_FA_SHUTTLE_SPACE oxorany("\xef\x86\x97")	// U+f197
#define ICON_FA_SIGN_HANGING oxorany("\xef\x93\x99")	// U+f4d9
#define ICON_FA_SIGNAL oxorany("\xef\x80\x92")	// U+f012
#define ICON_FA_SIGNATURE oxorany("\xef\x96\xb7")	// U+f5b7
#define ICON_FA_SIGNS_POST oxorany("\xef\x89\xb7")	// U+f277
#define ICON_FA_SIM_CARD oxorany("\xef\x9f\x84")	// U+f7c4
#define ICON_FA_SINK oxorany("\xee\x81\xad")	// U+e06d
#define ICON_FA_SITEMAP oxorany("\xef\x83\xa8")	// U+f0e8
#define ICON_FA_SKULL oxorany("\xef\x95\x8c")	// U+f54c
#define ICON_FA_SKULL_CROSSBONES oxorany("\xef\x9c\x94")	// U+f714
#define ICON_FA_SLASH oxorany("\xef\x9c\x95")	// U+f715
#define ICON_FA_SLEIGH oxorany("\xef\x9f\x8c")	// U+f7cc
#define ICON_FA_SLIDERS oxorany("\xef\x87\x9e")	// U+f1de
#define ICON_FA_SMOG oxorany("\xef\x9d\x9f")	// U+f75f
#define ICON_FA_SMOKING oxorany("\xef\x92\x8d")	// U+f48d
#define ICON_FA_SNOWFLAKE oxorany("\xef\x8b\x9c")	// U+f2dc
#define ICON_FA_SNOWMAN oxorany("\xef\x9f\x90")	// U+f7d0
#define ICON_FA_SNOWPLOW oxorany("\xef\x9f\x92")	// U+f7d2
#define ICON_FA_SOAP oxorany("\xee\x81\xae")	// U+e06e
#define ICON_FA_SOCKS oxorany("\xef\x9a\x96")	// U+f696
#define ICON_FA_SOLAR_PANEL oxorany("\xef\x96\xba")	// U+f5ba
#define ICON_FA_SORT oxorany("\xef\x83\x9c")	// U+f0dc
#define ICON_FA_SORT_DOWN oxorany("\xef\x83\x9d")	// U+f0dd
#define ICON_FA_SORT_UP oxorany("\xef\x83\x9e")	// U+f0de
#define ICON_FA_SPA oxorany("\xef\x96\xbb")	// U+f5bb
#define ICON_FA_SPAGHETTI_MONSTER_FLYING oxorany("\xef\x99\xbb")	// U+f67b
#define ICON_FA_SPELL_CHECK oxorany("\xef\xa2\x91")	// U+f891
#define ICON_FA_SPIDER oxorany("\xef\x9c\x97")	// U+f717
#define ICON_FA_SPINNER oxorany("\xef\x84\x90")	// U+f110
#define ICON_FA_SPLOTCH oxorany("\xef\x96\xbc")	// U+f5bc
#define ICON_FA_SPOON oxorany("\xef\x8b\xa5")	// U+f2e5
#define ICON_FA_SPRAY_CAN oxorany("\xef\x96\xbd")	// U+f5bd
#define ICON_FA_SPRAY_CAN_SPARKLES oxorany("\xef\x97\x90")	// U+f5d0
#define ICON_FA_SQUARE oxorany("\xef\x83\x88")	// U+f0c8
#define ICON_FA_SQUARE_ARROW_UP_RIGHT oxorany("\xef\x85\x8c")	// U+f14c
#define ICON_FA_SQUARE_CARET_DOWN oxorany("\xef\x85\x90")	// U+f150
#define ICON_FA_SQUARE_CARET_LEFT oxorany("\xef\x86\x91")	// U+f191
#define ICON_FA_SQUARE_CARET_RIGHT oxorany("\xef\x85\x92")	// U+f152
#define ICON_FA_SQUARE_CARET_UP oxorany("\xef\x85\x91")	// U+f151
#define ICON_FA_SQUARE_CHECK oxorany("\xef\x85\x8a")	// U+f14a
#define ICON_FA_SQUARE_ENVELOPE oxorany("\xef\x86\x99")	// U+f199
#define ICON_FA_SQUARE_FULL oxorany("\xef\x91\x9c")	// U+f45c
#define ICON_FA_SQUARE_H oxorany("\xef\x83\xbd")	// U+f0fd
#define ICON_FA_SQUARE_MINUS oxorany("\xef\x85\x86")	// U+f146
#define ICON_FA_SQUARE_NFI oxorany("\xee\x95\xb6")	// U+e576
#define ICON_FA_SQUARE_PARKING oxorany("\xef\x95\x80")	// U+f540
#define ICON_FA_SQUARE_PEN oxorany("\xef\x85\x8b")	// U+f14b
#define ICON_FA_SQUARE_PERSON_CONFINED oxorany("\xee\x95\xb7")	// U+e577
#define ICON_FA_SQUARE_PHONE oxorany("\xef\x82\x98")	// U+f098
#define ICON_FA_SQUARE_PHONE_FLIP oxorany("\xef\xa1\xbb")	// U+f87b
#define ICON_FA_SQUARE_PLUS oxorany("\xef\x83\xbe")	// U+f0fe
#define ICON_FA_SQUARE_POLL_HORIZONTAL oxorany("\xef\x9a\x82")	// U+f682
#define ICON_FA_SQUARE_POLL_VERTICAL oxorany("\xef\x9a\x81")	// U+f681
#define ICON_FA_SQUARE_ROOT_VARIABLE oxorany("\xef\x9a\x98")	// U+f698
#define ICON_FA_SQUARE_RSS oxorany("\xef\x85\x83")	// U+f143
#define ICON_FA_SQUARE_SHARE_NODES oxorany("\xef\x87\xa1")	// U+f1e1
#define ICON_FA_SQUARE_UP_RIGHT oxorany("\xef\x8d\xa0")	// U+f360
#define ICON_FA_SQUARE_VIRUS oxorany("\xee\x95\xb8")	// U+e578
#define ICON_FA_SQUARE_XMARK oxorany("\xef\x8b\x93")	// U+f2d3
#define ICON_FA_STAFF_AESCULAPIUS oxorany("\xee\x95\xb9")	// U+e579
#define ICON_FA_STAIRS oxorany("\xee\x8a\x89")	// U+e289
#define ICON_FA_STAMP oxorany("\xef\x96\xbf")	// U+f5bf
#define ICON_FA_STAR oxorany("\xef\x80\x85")	// U+f005
#define ICON_FA_STAR_AND_CRESCENT oxorany("\xef\x9a\x99")	// U+f699
#define ICON_FA_STAR_HALF oxorany("\xef\x82\x89")	// U+f089
#define ICON_FA_STAR_HALF_STROKE oxorany("\xef\x97\x80")	// U+f5c0
#define ICON_FA_STAR_OF_DAVID oxorany("\xef\x9a\x9a")	// U+f69a
#define ICON_FA_STAR_OF_LIFE oxorany("\xef\x98\xa1")	// U+f621
#define ICON_FA_STERLING_SIGN oxorany("\xef\x85\x94")	// U+f154
#define ICON_FA_STETHOSCOPE oxorany("\xef\x83\xb1")	// U+f0f1
#define ICON_FA_STOP oxorany("\xef\x81\x8d")	// U+f04d
#define ICON_FA_STOPWATCH oxorany("\xef\x8b\xb2")	// U+f2f2
#define ICON_FA_STOPWATCH_20 oxorany("\xee\x81\xaf")	// U+e06f
#define ICON_FA_STORE oxorany("\xef\x95\x8e")	// U+f54e
#define ICON_FA_STORE_SLASH oxorany("\xee\x81\xb1")	// U+e071
#define ICON_FA_STREET_VIEW oxorany("\xef\x88\x9d")	// U+f21d
#define ICON_FA_STRIKETHROUGH oxorany("\xef\x83\x8c")	// U+f0cc
#define ICON_FA_STROOPWAFEL oxorany("\xef\x95\x91")	// U+f551
#define ICON_FA_SUBSCRIPT oxorany("\xef\x84\xac")	// U+f12c
#define ICON_FA_SUITCASE oxorany("\xef\x83\xb2")	// U+f0f2
#define ICON_FA_SUITCASE_MEDICAL oxorany("\xef\x83\xba")	// U+f0fa
#define ICON_FA_SUITCASE_ROLLING oxorany("\xef\x97\x81")	// U+f5c1
#define ICON_FA_SUN oxorany("\xef\x86\x85")	// U+f185
#define ICON_FA_SUN_PLANT_WILT oxorany("\xee\x95\xba")	// U+e57a
#define ICON_FA_SUPERSCRIPT oxorany("\xef\x84\xab")	// U+f12b
#define ICON_FA_SWATCHBOOK oxorany("\xef\x97\x83")	// U+f5c3
#define ICON_FA_SYNAGOGUE oxorany("\xef\x9a\x9b")	// U+f69b
#define ICON_FA_SYRINGE oxorany("\xef\x92\x8e")	// U+f48e
#define ICON_FA_T oxorany("T")	// U+54
#define ICON_FA_TABLE oxorany("\xef\x83\x8e")	// U+f0ce
#define ICON_FA_TABLE_CELLS oxorany("\xef\x80\x8a")	// U+f00a
#define ICON_FA_TABLE_CELLS_LARGE oxorany("\xef\x80\x89")	// U+f009
#define ICON_FA_TABLE_COLUMNS oxorany("\xef\x83\x9b")	// U+f0db
#define ICON_FA_TABLE_LIST oxorany("\xef\x80\x8b")	// U+f00b
#define ICON_FA_TABLE_TENNIS_PADDLE_BALL oxorany("\xef\x91\x9d")	// U+f45d
#define ICON_FA_TABLET oxorany("\xef\x8f\xbb")	// U+f3fb
#define ICON_FA_TABLET_BUTTON oxorany("\xef\x84\x8a")	// U+f10a
#define ICON_FA_TABLET_SCREEN_BUTTON oxorany("\xef\x8f\xba")	// U+f3fa
#define ICON_FA_TABLETS oxorany("\xef\x92\x90")	// U+f490
#define ICON_FA_TACHOGRAPH_DIGITAL oxorany("\xef\x95\xa6")	// U+f566
#define ICON_FA_TAG oxorany("\xef\x80\xab")	// U+f02b
#define ICON_FA_TAGS oxorany("\xef\x80\xac")	// U+f02c
#define ICON_FA_TAPE oxorany("\xef\x93\x9b")	// U+f4db
#define ICON_FA_TARP oxorany("\xee\x95\xbb")	// U+e57b
#define ICON_FA_TARP_DROPLET oxorany("\xee\x95\xbc")	// U+e57c
#define ICON_FA_TAXI oxorany("\xef\x86\xba")	// U+f1ba
#define ICON_FA_TEETH oxorany("\xef\x98\xae")	// U+f62e
#define ICON_FA_TEETH_OPEN oxorany("\xef\x98\xaf")	// U+f62f
#define ICON_FA_TEMPERATURE_ARROW_DOWN oxorany("\xee\x80\xbf")	// U+e03f
#define ICON_FA_TEMPERATURE_ARROW_UP oxorany("\xee\x81\x80")	// U+e040
#define ICON_FA_TEMPERATURE_EMPTY oxorany("\xef\x8b\x8b")	// U+f2cb
#define ICON_FA_TEMPERATURE_FULL oxorany("\xef\x8b\x87")	// U+f2c7
#define ICON_FA_TEMPERATURE_HALF oxorany("\xef\x8b\x89")	// U+f2c9
#define ICON_FA_TEMPERATURE_HIGH oxorany("\xef\x9d\xa9")	// U+f769
#define ICON_FA_TEMPERATURE_LOW oxorany("\xef\x9d\xab")	// U+f76b
#define ICON_FA_TEMPERATURE_QUARTER oxorany("\xef\x8b\x8a")	// U+f2ca
#define ICON_FA_TEMPERATURE_THREE_QUARTERS oxorany("\xef\x8b\x88")	// U+f2c8
#define ICON_FA_TENGE_SIGN oxorany("\xef\x9f\x97")	// U+f7d7
#define ICON_FA_TENT oxorany("\xee\x95\xbd")	// U+e57d
#define ICON_FA_TENT_ARROW_DOWN_TO_LINE oxorany("\xee\x95\xbe")	// U+e57e
#define ICON_FA_TENT_ARROW_LEFT_RIGHT oxorany("\xee\x95\xbf")	// U+e57f
#define ICON_FA_TENT_ARROW_TURN_LEFT oxorany("\xee\x96\x80")	// U+e580
#define ICON_FA_TENT_ARROWS_DOWN oxorany("\xee\x96\x81")	// U+e581
#define ICON_FA_TENTS oxorany("\xee\x96\x82")	// U+e582
#define ICON_FA_TERMINAL oxorany("\xef\x84\xa0")	// U+f120
#define ICON_FA_TEXT_HEIGHT oxorany("\xef\x80\xb4")	// U+f034
#define ICON_FA_TEXT_SLASH oxorany("\xef\xa1\xbd")	// U+f87d
#define ICON_FA_TEXT_WIDTH oxorany("\xef\x80\xb5")	// U+f035
#define ICON_FA_THERMOMETER oxorany("\xef\x92\x91")	// U+f491
#define ICON_FA_THUMBS_DOWN oxorany("\xef\x85\xa5")	// U+f165
#define ICON_FA_THUMBS_UP oxorany("\xef\x85\xa4")	// U+f164
#define ICON_FA_THUMBTACK oxorany("\xef\x82\x8d")	// U+f08d
#define ICON_FA_TICKET oxorany("\xef\x85\x85")	// U+f145
#define ICON_FA_TICKET_SIMPLE oxorany("\xef\x8f\xbf")	// U+f3ff
#define ICON_FA_TIMELINE oxorany("\xee\x8a\x9c")	// U+e29c
#define ICON_FA_TOGGLE_OFF oxorany("\xef\x88\x84")	// U+f204
#define ICON_FA_TOGGLE_ON oxorany("\xef\x88\x85")	// U+f205
#define ICON_FA_TOILET oxorany("\xef\x9f\x98")	// U+f7d8
#define ICON_FA_TOILET_PAPER oxorany("\xef\x9c\x9e")	// U+f71e
#define ICON_FA_TOILET_PAPER_SLASH oxorany("\xee\x81\xb2")	// U+e072
#define ICON_FA_TOILET_PORTABLE oxorany("\xee\x96\x83")	// U+e583
#define ICON_FA_TOILETS_PORTABLE oxorany("\xee\x96\x84")	// U+e584
#define ICON_FA_TOOLBOX oxorany("\xef\x95\x92")	// U+f552
#define ICON_FA_TOOTH oxorany("\xef\x97\x89")	// U+f5c9
#define ICON_FA_TORII_GATE oxorany("\xef\x9a\xa1")	// U+f6a1
#define ICON_FA_TORNADO oxorany("\xef\x9d\xaf")	// U+f76f
#define ICON_FA_TOWER_BROADCAST oxorany("\xef\x94\x99")	// U+f519
#define ICON_FA_TOWER_CELL oxorany("\xee\x96\x85")	// U+e585
#define ICON_FA_TOWER_OBSERVATION oxorany("\xee\x96\x86")	// U+e586
#define ICON_FA_TRACTOR oxorany("\xef\x9c\xa2")	// U+f722
#define ICON_FA_TRADEMARK oxorany("\xef\x89\x9c")	// U+f25c
#define ICON_FA_TRAFFIC_LIGHT oxorany("\xef\x98\xb7")	// U+f637
#define ICON_FA_TRAILER oxorany("\xee\x81\x81")	// U+e041
#define ICON_FA_TRAIN oxorany("\xef\x88\xb8")	// U+f238
#define ICON_FA_TRAIN_SUBWAY oxorany("\xef\x88\xb9")	// U+f239
#define ICON_FA_TRAIN_TRAM oxorany("\xef\x9f\x9a")	// U+f7da
#define ICON_FA_TRANSGENDER oxorany("\xef\x88\xa5")	// U+f225
#define ICON_FA_TRASH oxorany("\xef\x87\xb8")	// U+f1f8
#define ICON_FA_TRASH_ARROW_UP oxorany("\xef\xa0\xa9")	// U+f829
#define ICON_FA_TRASH_CAN oxorany("\xef\x8b\xad")	// U+f2ed
#define ICON_FA_TRASH_CAN_ARROW_UP oxorany("\xef\xa0\xaa")	// U+f82a
#define ICON_FA_TREE oxorany("\xef\x86\xbb")	// U+f1bb
#define ICON_FA_TREE_CITY oxorany("\xee\x96\x87")	// U+e587
#define ICON_FA_TRIANGLE_EXCLAMATION oxorany("\xef\x81\xb1")	// U+f071
#define ICON_FA_TROPHY oxorany("\xef\x82\x91")	// U+f091
#define ICON_FA_TROWEL oxorany("\xee\x96\x89")	// U+e589
#define ICON_FA_TROWEL_BRICKS oxorany("\xee\x96\x8a")	// U+e58a
#define ICON_FA_TRUCK oxorany("\xef\x83\x91")	// U+f0d1
#define ICON_FA_TRUCK_ARROW_RIGHT oxorany("\xee\x96\x8b")	// U+e58b
#define ICON_FA_TRUCK_DROPLET oxorany("\xee\x96\x8c")	// U+e58c
#define ICON_FA_TRUCK_FAST oxorany("\xef\x92\x8b")	// U+f48b
#define ICON_FA_TRUCK_FIELD oxorany("\xee\x96\x8d")	// U+e58d
#define ICON_FA_TRUCK_FIELD_UN oxorany("\xee\x96\x8e")	// U+e58e
#define ICON_FA_TRUCK_FRONT oxorany("\xee\x8a\xb7")	// U+e2b7
#define ICON_FA_TRUCK_MEDICAL oxorany("\xef\x83\xb9")	// U+f0f9
#define ICON_FA_TRUCK_MONSTER oxorany("\xef\x98\xbb")	// U+f63b
#define ICON_FA_TRUCK_MOVING oxorany("\xef\x93\x9f")	// U+f4df
#define ICON_FA_TRUCK_PICKUP oxorany("\xef\x98\xbc")	// U+f63c
#define ICON_FA_TRUCK_PLANE oxorany("\xee\x96\x8f")	// U+e58f
#define ICON_FA_TRUCK_RAMP_BOX oxorany("\xef\x93\x9e")	// U+f4de
#define ICON_FA_TTY oxorany("\xef\x87\xa4")	// U+f1e4
#define ICON_FA_TURKISH_LIRA_SIGN oxorany("\xee\x8a\xbb")	// U+e2bb
#define ICON_FA_TURN_DOWN oxorany("\xef\x8e\xbe")	// U+f3be
#define ICON_FA_TURN_UP oxorany("\xef\x8e\xbf")	// U+f3bf
#define ICON_FA_TV oxorany("\xef\x89\xac")	// U+f26c
#define ICON_FA_U oxorany("U")	// U+55
#define ICON_FA_UMBRELLA oxorany("\xef\x83\xa9")	// U+f0e9
#define ICON_FA_UMBRELLA_BEACH oxorany("\xef\x97\x8a")	// U+f5ca
#define ICON_FA_UNDERLINE oxorany("\xef\x83\x8d")	// U+f0cd
#define ICON_FA_UNIVERSAL_ACCESS oxorany("\xef\x8a\x9a")	// U+f29a
#define ICON_FA_UNLOCK oxorany("\xef\x82\x9c")	// U+f09c
#define ICON_FA_UNLOCK_KEYHOLE oxorany("\xef\x84\xbe")	// U+f13e
#define ICON_FA_UP_DOWN oxorany("\xef\x8c\xb8")	// U+f338
#define ICON_FA_UP_DOWN_LEFT_RIGHT oxorany("\xef\x82\xb2")	// U+f0b2
#define ICON_FA_UP_LONG oxorany("\xef\x8c\x8c")	// U+f30c
#define ICON_FA_UP_RIGHT_AND_DOWN_LEFT_FROM_CENTER oxorany("\xef\x90\xa4")	// U+f424
#define ICON_FA_UP_RIGHT_FROM_SQUARE oxorany("\xef\x8d\x9d")	// U+f35d
#define ICON_FA_UPLOAD oxorany("\xef\x82\x93")	// U+f093
#define ICON_FA_USER oxorany("\xef\x80\x87")	// U+f007
#define ICON_FA_USER_ASTRONAUT oxorany("\xef\x93\xbb")	// U+f4fb
#define ICON_FA_USER_CHECK oxorany("\xef\x93\xbc")	// U+f4fc
#define ICON_FA_USER_CLOCK oxorany("\xef\x93\xbd")	// U+f4fd
#define ICON_FA_USER_DOCTOR oxorany("\xef\x83\xb0")	// U+f0f0
#define ICON_FA_USER_GEAR oxorany("\xef\x93\xbe")	// U+f4fe
#define ICON_FA_USER_GRADUATE oxorany("\xef\x94\x81")	// U+f501
#define ICON_FA_USER_GROUP oxorany("\xef\x94\x80")	// U+f500
#define ICON_FA_USER_INJURED oxorany("\xef\x9c\xa8")	// U+f728
#define ICON_FA_USER_LARGE oxorany("\xef\x90\x86")	// U+f406
#define ICON_FA_USER_LARGE_SLASH oxorany("\xef\x93\xba")	// U+f4fa
#define ICON_FA_USER_LOCK oxorany("\xef\x94\x82")	// U+f502
#define ICON_FA_USER_MINUS oxorany("\xef\x94\x83")	// U+f503
#define ICON_FA_USER_NINJA oxorany("\xef\x94\x84")	// U+f504
#define ICON_FA_USER_NURSE oxorany("\xef\xa0\xaf")	// U+f82f
#define ICON_FA_USER_PEN oxorany("\xef\x93\xbf")	// U+f4ff
#define ICON_FA_USER_PLUS oxorany("\xef\x88\xb4")	// U+f234
#define ICON_FA_USER_SECRET oxorany("\xef\x88\x9b")	// U+f21b
#define ICON_FA_USER_SHIELD oxorany("\xef\x94\x85")	// U+f505
#define ICON_FA_USER_SLASH oxorany("\xef\x94\x86")	// U+f506
#define ICON_FA_USER_TAG oxorany("\xef\x94\x87")	// U+f507
#define ICON_FA_USER_TIE oxorany("\xef\x94\x88")	// U+f508
#define ICON_FA_USER_XMARK oxorany("\xef\x88\xb5")	// U+f235
#define ICON_FA_USERS oxorany("\xef\x83\x80")	// U+f0c0
#define ICON_FA_USERS_BETWEEN_LINES oxorany("\xee\x96\x91")	// U+e591
#define ICON_FA_USERS_GEAR oxorany("\xef\x94\x89")	// U+f509
#define ICON_FA_USERS_LINE oxorany("\xee\x96\x92")	// U+e592
#define ICON_FA_USERS_RAYS oxorany("\xee\x96\x93")	// U+e593
#define ICON_FA_USERS_RECTANGLE oxorany("\xee\x96\x94")	// U+e594
#define ICON_FA_USERS_SLASH oxorany("\xee\x81\xb3")	// U+e073
#define ICON_FA_USERS_VIEWFINDER oxorany("\xee\x96\x95")	// U+e595
#define ICON_FA_UTENSILS oxorany("\xef\x8b\xa7")	// U+f2e7
#define ICON_FA_V oxorany("V")	// U+56
#define ICON_FA_VAN_SHUTTLE oxorany("\xef\x96\xb6")	// U+f5b6
#define ICON_FA_VAULT oxorany("\xee\x8b\x85")	// U+e2c5
#define ICON_FA_VECTOR_SQUARE oxorany("\xef\x97\x8b")	// U+f5cb
#define ICON_FA_VENUS oxorany("\xef\x88\xa1")	// U+f221
#define ICON_FA_VENUS_DOUBLE oxorany("\xef\x88\xa6")	// U+f226
#define ICON_FA_VENUS_MARS oxorany("\xef\x88\xa8")	// U+f228
#define ICON_FA_VEST oxorany("\xee\x82\x85")	// U+e085
#define ICON_FA_VEST_PATCHES oxorany("\xee\x82\x86")	// U+e086
#define ICON_FA_VIAL oxorany("\xef\x92\x92")	// U+f492
#define ICON_FA_VIAL_CIRCLE_CHECK oxorany("\xee\x96\x96")	// U+e596
#define ICON_FA_VIAL_VIRUS oxorany("\xee\x96\x97")	// U+e597
#define ICON_FA_VIALS oxorany("\xef\x92\x93")	// U+f493
#define ICON_FA_VIDEO oxorany("\xef\x80\xbd")	// U+f03d
#define ICON_FA_VIDEO_SLASH oxorany("\xef\x93\xa2")	// U+f4e2
#define ICON_FA_VIHARA oxorany("\xef\x9a\xa7")	// U+f6a7
#define ICON_FA_VIRUS oxorany("\xee\x81\xb4")	// U+e074
#define ICON_FA_VIRUS_COVID oxorany("\xee\x92\xa8")	// U+e4a8
#define ICON_FA_VIRUS_COVID_SLASH oxorany("\xee\x92\xa9")	// U+e4a9
#define ICON_FA_VIRUS_SLASH oxorany("\xee\x81\xb5")	// U+e075
#define ICON_FA_VIRUSES oxorany("\xee\x81\xb6")	// U+e076
#define ICON_FA_VOICEMAIL oxorany("\xef\xa2\x97")	// U+f897
#define ICON_FA_VOLCANO oxorany("\xef\x9d\xb0")	// U+f770
#define ICON_FA_VOLLEYBALL oxorany("\xef\x91\x9f")	// U+f45f
#define ICON_FA_VOLUME_HIGH oxorany("\xef\x80\xa8")	// U+f028
#define ICON_FA_VOLUME_LOW oxorany("\xef\x80\xa7")	// U+f027
#define ICON_FA_VOLUME_OFF oxorany("\xef\x80\xa6")	// U+f026
#define ICON_FA_VOLUME_XMARK oxorany("\xef\x9a\xa9")	// U+f6a9
#define ICON_FA_VR_CARDBOARD oxorany("\xef\x9c\xa9")	// U+f729
#define ICON_FA_W oxorany("W")	// U+57
#define ICON_FA_WALKIE_TALKIE oxorany("\xef\xa3\xaf")	// U+f8ef
#define ICON_FA_WALLET oxorany("\xef\x95\x95")	// U+f555
#define ICON_FA_WAND_MAGIC oxorany("\xef\x83\x90")	// U+f0d0
#define ICON_FA_WAND_MAGIC_SPARKLES oxorany("\xee\x8b\x8a")	// U+e2ca
#define ICON_FA_WAND_SPARKLES oxorany("\xef\x9c\xab")	// U+f72b
#define ICON_FA_WAREHOUSE oxorany("\xef\x92\x94")	// U+f494
#define ICON_FA_WATER oxorany("\xef\x9d\xb3")	// U+f773
#define ICON_FA_WATER_LADDER oxorany("\xef\x97\x85")	// U+f5c5
#define ICON_FA_WAVE_SQUARE oxorany("\xef\xa0\xbe")	// U+f83e
#define ICON_FA_WEIGHT_HANGING oxorany("\xef\x97\x8d")	// U+f5cd
#define ICON_FA_WEIGHT_SCALE oxorany("\xef\x92\x96")	// U+f496
#define ICON_FA_WHEAT_AWN oxorany("\xee\x8b\x8d")	// U+e2cd
#define ICON_FA_WHEAT_AWN_CIRCLE_EXCLAMATION oxorany("\xee\x96\x98")	// U+e598
#define ICON_FA_WHEELCHAIR oxorany("\xef\x86\x93")	// U+f193
#define ICON_FA_WHEELCHAIR_MOVE oxorany("\xee\x8b\x8e")	// U+e2ce
#define ICON_FA_WHISKEY_GLASS oxorany("\xef\x9e\xa0")	// U+f7a0
#define ICON_FA_WIFI oxorany("\xef\x87\xab")	// U+f1eb
#define ICON_FA_WIND oxorany("\xef\x9c\xae")	// U+f72e
#define ICON_FA_WINDOW_MAXIMIZE oxorany("\xef\x8b\x90")	// U+f2d0
#define ICON_FA_WINDOW_MINIMIZE oxorany("\xef\x8b\x91")	// U+f2d1
#define ICON_FA_WINDOW_RESTORE oxorany("\xef\x8b\x92")	// U+f2d2
#define ICON_FA_WINE_BOTTLE oxorany("\xef\x9c\xaf")	// U+f72f
#define ICON_FA_WINE_GLASS oxorany("\xef\x93\xa3")	// U+f4e3
#define ICON_FA_WINE_GLASS_EMPTY oxorany("\xef\x97\x8e")	// U+f5ce
#define ICON_FA_WON_SIGN oxorany("\xef\x85\x99")	// U+f159
#define ICON_FA_WORM oxorany("\xee\x96\x99")	// U+e599
#define ICON_FA_WRENCH oxorany("\xef\x82\xad")	// U+f0ad
#define ICON_FA_X oxorany("X")	// U+58
#define ICON_FA_X_RAY oxorany("\xef\x92\x97")	// U+f497
#define ICON_FA_XMARK oxorany("\xef\x80\x8d")	// U+f00d
#define ICON_FA_XMARKS_LINES oxorany("\xee\x96\x9a")	// U+e59a
#define ICON_FA_Y oxorany("Y")	// U+59
#define ICON_FA_YEN_SIGN oxorany("\xef\x85\x97")	// U+f157
#define ICON_FA_YIN_YANG oxorany("\xef\x9a\xad")	// U+f6ad
#define ICON_FA_Z oxorany("Z")	// U+5a
